# Generated by Django 4.2.7 on 2025-10-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_premiumfeature_premiumsubscription_featureusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BenchmarkAnalytics',
        ),
        migrations.AlterUniqueTogether(
            name='benchmarkcomparison',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='benchmarkcomparison',
            name='user',
        ),
        migrations.DeleteModel(
            name='BenchmarkPerformanceHistory',
        ),
        migrations.AlterUniqueTogether(
            name='custombenchmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='custombenchmark',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='custombenchmarkholding',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='custombenchmarkholding',
            name='benchmark',
        ),
        migrations.AddField(
            model_name='cryptotrade',
            name='executed_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptotrade',
            name='executed_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptotrade',
            name='order_type',
            field=models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP_MARKET', 'Stop Market'), ('STOP_LIMIT', 'Stop Limit')], default='MARKET', max_length=20),
        ),
        migrations.AddField(
            model_name='cryptotrade',
            name='quote_source',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cryptotrade',
            name='quote_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptotrade',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cryptotrade',
            name='slippage_bps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptotrade',
            name='time_in_force',
            field=models.CharField(choices=[('GTC', 'Good Till Cancel'), ('IOC', 'Immediate or Cancel'), ('FOK', 'Fill or Kill')], default='GTC', max_length=10),
        ),
        migrations.DeleteModel(
            name='BenchmarkComparison',
        ),
        migrations.DeleteModel(
            name='CustomBenchmark',
        ),
        migrations.DeleteModel(
            name='CustomBenchmarkHolding',
        ),
    ]
