# Generated by Django 4.2.7 on 2025-10-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_benchmarkanalytics_and_more'),
    ]

    operations = [
    ]
