# Generated by Django 4.2.7 on 2025-10-16 20:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20251016_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=32)),
                ('rpc_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['chain_id'],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_audited', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_address', models.CharField(db_index=True, max_length=66)),
                ('router_address', models.CharField(blank=True, max_length=66, null=True)),
                ('gauge_address', models.CharField(blank=True, max_length=66, null=True)),
                ('token0', models.CharField(max_length=64)),
                ('token1', models.CharField(blank=True, max_length=64)),
                ('token0_decimals', models.PositiveIntegerField(default=6)),
                ('token1_decimals', models.PositiveIntegerField(default=18)),
                ('lp_decimals', models.PositiveIntegerField(default=18)),
                ('symbol', models.CharField(max_length=64)),
                ('tvl_usd', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('apy_base', models.FloatField(default=0)),
                ('apy_reward', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.chain')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.protocol')),
            ],
            options={
                'ordering': ['-tvl_usd'],
            },
        ),
        migrations.CreateModel(
            name='FarmPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(db_index=True, max_length=66)),
                ('staked_lp', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=38)),
                ('rewards_earned', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=38)),
                ('realized_apy', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('action', models.CharField(choices=[('STAKE', 'Stake'), ('UNSTAKE', 'Unstake'), ('HARVEST', 'Harvest'), ('CLAIM', 'Claim Rewards')], max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('gas_price', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.farmposition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.UniqueConstraint(fields=('chain', 'pool_address'), name='uniq_pool_per_chain'),
        ),
    ]
