# Generated by Django 4.2.7 on 2025-10-17 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_defi_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('apy_base', models.FloatField()),
                ('apy_reward', models.FloatField()),
                ('total_apy', models.FloatField()),
                ('tvl_usd', models.DecimalField(decimal_places=6, max_digits=24)),
                ('volume_24h_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_history', to='core.pool')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['pool', 'timestamp'], name='core_yieldh_pool_id_66b2a9_idx'), models.Index(fields=['timestamp'], name='core_yieldh_timesta_fe807e_idx')],
                'unique_together': {('pool', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('staked_lp', models.DecimalField(decimal_places=18, max_digits=38)),
                ('rewards_earned', models.DecimalField(decimal_places=18, max_digits=38)),
                ('total_value_usd', models.DecimalField(decimal_places=6, max_digits=24)),
                ('realized_apy', models.FloatField()),
                ('pool_apy', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.farmposition')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['position', 'timestamp'], name='core_positi_positio_a0d06c_idx'), models.Index(fields=['timestamp'], name='core_positi_timesta_50ad69_idx')],
                'unique_together': {('position', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value_usd', models.DecimalField(decimal_places=6, max_digits=24)),
                ('weighted_apy', models.FloatField()),
                ('portfolio_risk', models.FloatField()),
                ('diversification_score', models.FloatField()),
                ('active_positions', models.IntegerField()),
                ('protocols_count', models.IntegerField()),
                ('total_return_1d', models.FloatField(blank=True, null=True)),
                ('total_return_7d', models.FloatField(blank=True, null=True)),
                ('total_return_30d', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='core_portfo_user_id_20ddca_idx'), models.Index(fields=['date'], name='core_portfo_date_7444b5_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PoolAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fee_apy', models.FloatField(blank=True, null=True)),
                ('il_estimate', models.FloatField(blank=True, null=True)),
                ('net_apy', models.FloatField(blank=True, null=True)),
                ('volume_24h_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('tvl_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.pool')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['pool', 'date'], name='core_poolan_pool_id_fd52bd_idx'), models.Index(fields=['date'], name='core_poolan_date_32276a_idx')],
                'unique_together': {('pool', 'date')},
            },
        ),
    ]
