# Generated by Django 5.1.4 on 2025-10-19 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_yieldhistory_positionsnapshot_portfoliometrics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertdeliveryhistory',
            name='alert',
        ),
        migrations.AlterUniqueTogether(
            name='alertdeliverypreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='alertdeliverypreference',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='alertsuppression',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='alertsuppression',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='alertthreshold',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='alertthreshold',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='banktransaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='farmaction',
            name='position',
        ),
        migrations.RemoveField(
            model_name='farmposition',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='farmposition',
            name='user',
        ),
        migrations.RemoveField(
            model_name='positionsnapshot',
            name='position',
        ),
        migrations.RemoveField(
            model_name='mlanomalydetection',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='mlanomalydetection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='poolanalytics',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='yieldhistory',
            name='pool',
        ),
        migrations.AlterUniqueTogether(
            name='poolanalytics',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='portfoliometrics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='portfoliometrics',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='positionsnapshot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='smartalert',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='yieldhistory',
            unique_together=None,
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='banklink',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='bankaccount',
            name='core_bankac_link_id_f5cf1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankaccount',
            name='core_bankac_account_75fc82_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankaccount',
            name='core_bankac_last_up_0e4394_idx',
        ),
        migrations.RemoveIndex(
            model_name='banklink',
            name='core_bankli_user_id_245cf5_idx',
        ),
        migrations.RemoveIndex(
            model_name='banklink',
            name='core_bankli_provide_63ca92_idx',
        ),
        migrations.RemoveIndex(
            model_name='banklink',
            name='core_bankli_last_sy_e49934_idx',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='link',
            new_name='bank_link',
        ),
        migrations.RenameField(
            model_name='banklink',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='banklink',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='banklink',
            name='institution_id',
        ),
        migrations.RemoveField(
            model_name='banklink',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='banklink',
            name='last_refresh',
        ),
        migrations.RemoveField(
            model_name='banklink',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='banklink',
            name='provider_account_id',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_number_masked',
            field=models.CharField(default='', help_text='Masked account number', max_length=50),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('CREDIT', 'Credit Card'), ('LOAN', 'Loan'), ('INVESTMENT', 'Investment'), ('OTHER', 'Other')], default='CHECKING', max_length=20),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='yodlee_account_id',
            field=models.CharField(default='', help_text="Yodlee's unique account ID", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='banklink',
            name='account_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='banklink',
            name='bank_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banklink',
            name='yodlee_account_id',
            field=models.CharField(default='', help_text="Yodlee's unique account ID", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='crypto_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total crypto portfolio value in USD', max_digits=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='crypto_enabled',
            field=models.BooleanField(default=False, help_text='Whether crypto trading is enabled for this portfolio'),
        ),
        migrations.AlterField(
            model_name='aiportfoliorecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiRecommendations', to='core.user'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.user'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='banklink',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='banklink',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ERROR', 'Error'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrowposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defi_borrows', to='core.user'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='core.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.user'),
        ),
        migrations.AlterField(
            model_name='cryptoeducationprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_education', to='core.user'),
        ),
        migrations.AlterField(
            model_name='cryptoportfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_portfolio', to='core.user'),
        ),
        migrations.AlterField(
            model_name='cryptosblocloan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_sbloc_loans', to='core.user'),
        ),
        migrations.AlterField(
            model_name='cryptotrade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_trades', to='core.user'),
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to='core.user'),
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to='core.user'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='core.user'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='core.user'),
        ),
        migrations.AlterField(
            model_name='incomeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incomeProfile', to='core.user'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.user'),
        ),
        migrations.AlterField(
            model_name='mlmodelversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='core.user'),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='core.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.user'),
        ),
        migrations.AlterField(
            model_name='stockdiscussion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_discussions', to='core.user'),
        ),
        migrations.AlterField(
            model_name='stockdiscussion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_discussions', to='core.user'),
        ),
        migrations.AlterField(
            model_name='supplyposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defi_supplies', to='core.user'),
        ),
        migrations.AlterField(
            model_name='tickerfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_follows', to='core.user'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='core.user'),
        ),
        migrations.DeleteModel(
            name='AlertDeliveryHistory',
        ),
        migrations.DeleteModel(
            name='AlertDeliveryPreference',
        ),
        migrations.DeleteModel(
            name='AlertSuppression',
        ),
        migrations.DeleteModel(
            name='AlertThreshold',
        ),
        migrations.DeleteModel(
            name='BankTransaction',
        ),
        migrations.DeleteModel(
            name='Chain',
        ),
        migrations.DeleteModel(
            name='FarmAction',
        ),
        migrations.DeleteModel(
            name='FarmPosition',
        ),
        migrations.DeleteModel(
            name='PositionSnapshot',
        ),
        migrations.DeleteModel(
            name='MLAnomalyDetection',
        ),
        migrations.DeleteModel(
            name='Protocol',
        ),
        migrations.DeleteModel(
            name='PoolAnalytics',
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
        migrations.DeleteModel(
            name='YieldHistory',
        ),
        migrations.DeleteModel(
            name='PortfolioMetrics',
        ),
        migrations.DeleteModel(
            name='SmartAlert',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_manual',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='mask',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='type',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='updated_at',
        ),
    ]
