# Generated by Django 5.1.4 on 2025-10-19 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_alertdeliveryhistory_alert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlpacaAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alpaca_account_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('account_type', models.CharField(default='individual', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField()),
                ('ssn', models.CharField(blank=True, max_length=11)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='US', max_length=50)),
                ('employment_status', models.CharField(blank=True, max_length=50)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_worth', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('risk_tolerance', models.CharField(default='medium', max_length=20)),
                ('investment_experience', models.CharField(default='beginner', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('alpaca_created_at', models.DateTimeField(blank=True, null=True)),
                ('alpaca_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alpaca_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alpaca Account',
                'verbose_name_plural': 'Alpaca Accounts',
                'db_table': 'alpaca_accounts',
            },
        ),
        migrations.CreateModel(
            name='AlpacaActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alpaca_activity_id', models.CharField(max_length=100, unique=True)),
                ('activity_type', models.CharField(choices=[('fill', 'Fill'), ('partial_fill', 'Partial Fill'), ('cancel', 'Cancel'), ('expire', 'Expire'), ('reject', 'Reject'), ('dividend', 'Dividend'), ('interest', 'Interest'), ('fee', 'Fee'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alpaca_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.alpacaaccount')),
            ],
            options={
                'verbose_name': 'Alpaca Activity',
                'verbose_name_plural': 'Alpaca Activities',
                'db_table': 'alpaca_activities',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='AlpacaKycDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('identity', 'Identity Document'), ('address', 'Address Verification'), ('income', 'Income Verification'), ('tax', 'Tax Document'), ('other', 'Other')], max_length=20)),
                ('document_name', models.CharField(max_length=200)),
                ('alpaca_document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('alpaca_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='core.alpacaaccount')),
            ],
            options={
                'verbose_name': 'Alpaca KYC Document',
                'verbose_name_plural': 'Alpaca KYC Documents',
                'db_table': 'alpaca_kyc_documents',
            },
        ),
        migrations.CreateModel(
            name='AlpacaOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alpaca_order_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop_limit', 'Stop Limit')], max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=15)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('time_in_force', models.CharField(choices=[('day', 'Day'), ('gtc', 'Good Till Canceled'), ('ioc', 'Immediate or Cancel'), ('fok', 'Fill or Kill')], default='day', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('rejected', 'Rejected')], max_length=20)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('average_fill_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('alpaca_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.alpacaaccount')),
            ],
            options={
                'verbose_name': 'Alpaca Order',
                'verbose_name_plural': 'Alpaca Orders',
                'db_table': 'alpaca_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlpacaPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=15)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unrealized_plpc', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alpaca_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.alpacaaccount')),
            ],
            options={
                'verbose_name': 'Alpaca Position',
                'verbose_name_plural': 'Alpaca Positions',
                'db_table': 'alpaca_positions',
                'unique_together': {('alpaca_account', 'symbol')},
            },
        ),
    ]
