# Generated by Django 5.2.5 on 2025-10-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_create_alpaca_accounts"),
    ]

    operations = []
