# Generated by Django 5.2.5 on 2025-10-25 17:42

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_merge_20251025_1735"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveStream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("circle_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("market-analysis", "Market Analysis"),
                            ("portfolio-review", "Portfolio Review"),
                            ("qa", "Q&A Session"),
                            ("general", "General Discussion"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "stream_key",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("rtmp_url", models.URLField(blank=True, null=True)),
                ("hls_url", models.URLField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("max_viewers", models.PositiveIntegerField(default=0)),
                ("total_viewers", models.PositiveIntegerField(default=0)),
                ("total_reactions", models.PositiveIntegerField(default=0)),
                ("total_messages", models.PositiveIntegerField(default=0)),
                ("is_public", models.BooleanField(default=True)),
                ("allow_chat", models.BooleanField(default=True)),
                ("allow_reactions", models.BooleanField(default=True)),
                ("allow_screen_share", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_streams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QASession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_sessions",
                        to="core.livestream",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StreamPoll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_multiple_choice", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_votes", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to="core.livestream",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StreamMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("message", "Chat Message"),
                            ("system", "System Message"),
                            ("announcement", "Announcement"),
                            ("moderation", "Moderation"),
                        ],
                        default="message",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("replies", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.livestream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StreamReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("heart", "❤️ Heart"),
                            ("fire", "🔥 Fire"),
                            ("money", "💰 Money"),
                            ("thumbs", "👍 Thumbs Up"),
                            ("clap", "👏 Clap"),
                            ("laugh", "😂 Laugh"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="core.livestream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StreamViewer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "total_watch_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("reactions_sent", models.PositiveIntegerField(default=0)),
                ("messages_sent", models.PositiveIntegerField(default=0)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewers",
                        to="core.livestream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_viewings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScreenShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("share_type", models.CharField(default="screen", max_length=20)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screen_shares",
                        to="core.livestream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screen_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="QAQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("answered", "Answered"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("answer", models.TextField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("upvotes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qa_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.qasession",
                    ),
                ),
            ],
            options={
                "ordering": ["-upvotes", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("vote_count", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.streampoll",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PollVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to="core.polloption",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="core.streampoll",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(
                fields=["status", "created_at"], name="core_livest_status_cefd59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(
                fields=["circle_id", "status"], name="core_livest_circle__63a62c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(
                fields=["host", "status"], name="core_livest_host_id_4de9fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qaquestion",
            index=models.Index(
                fields=["qa_session", "status"], name="core_qaques_qa_sess_be23da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qaquestion",
            index=models.Index(
                fields=["user", "created_at"], name="core_qaques_user_id_ddb9d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="screenshare",
            index=models.Index(
                fields=["stream", "is_active"], name="core_screen_stream__a5a62e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streammessage",
            index=models.Index(
                fields=["stream", "created_at"], name="core_stream_stream__6e7a9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streammessage",
            index=models.Index(
                fields=["user", "created_at"], name="core_stream_user_id_4e543e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streammessage",
            index=models.Index(
                fields=["message_type", "created_at"],
                name="core_stream_message_60a560_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="streampoll",
            index=models.Index(
                fields=["stream", "is_active"], name="core_stream_stream__b98b7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streampoll",
            index=models.Index(
                fields=["created_at"], name="core_stream_created_f4ac9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pollvote",
            index=models.Index(
                fields=["poll", "created_at"], name="core_pollvo_poll_id_984e9a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pollvote",
            unique_together={("poll", "user", "option")},
        ),
        migrations.AlterUniqueTogether(
            name="polloption",
            unique_together={("poll", "order")},
        ),
        migrations.AddIndex(
            model_name="streamreaction",
            index=models.Index(
                fields=["stream", "created_at"], name="core_stream_stream__2281a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streamreaction",
            index=models.Index(
                fields=["reaction_type", "created_at"],
                name="core_stream_reactio_38c13e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="streamreaction",
            unique_together={("stream", "user", "reaction_type")},
        ),
        migrations.AddIndex(
            model_name="streamviewer",
            index=models.Index(
                fields=["stream", "is_active"], name="core_stream_stream__752ed5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streamviewer",
            index=models.Index(
                fields=["user", "joined_at"], name="core_stream_user_id_5ce0f9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="streamviewer",
            unique_together={("stream", "user")},
        ),
    ]
