# Generated by Django 5.2.5 on 2025-09-01 00:05
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
    ('core', '0010_add_watchlist_fields'),
    ]
    operations = [
    migrations.CreateModel(
    name='AIPortfolioRecommendation',
    fields=[
    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('risk_profile', models.CharField(max_length=50)),
    ('portfolio_allocation', models.JSONField()),
    ('expected_portfolio_return', models.CharField(max_length=20)),
    ('risk_assessment', models.CharField(max_length=50)),
    ('created_at', models.DateTimeField(auto_now_add=True)),
    ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiRecommendations', to=settings.AUTH_USER_MODEL)),
    ],
    options={
    'ordering': ['-created_at'],
    },
    ),
    migrations.CreateModel(
    name='IncomeProfile',
    fields=[
    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('income_bracket', models.CharField(max_length=50)),
    ('age', models.IntegerField()),
    ('investment_goals', models.JSONField(default=list)),
    ('risk_tolerance', models.CharField(max_length=20)),
    ('investment_horizon', models.CharField(max_length=20)),
    ('created_at', models.DateTimeField(auto_now_add=True)),
    ('updated_at', models.DateTimeField(auto_now=True)),
    ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incomeProfile', to=settings.AUTH_USER_MODEL)),
    ],
    options={
    'ordering': ['-updated_at'],
    },
    ),
    migrations.CreateModel(
    name='StockRecommendation',
    fields=[
    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('allocation', models.DecimalField(decimal_places=2, max_digits=5)),
    ('reasoning', models.TextField()),
    ('risk_level', models.CharField(max_length=20)),
    ('expected_return', models.CharField(max_length=20)),
    ('portfolio_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendedStocks', to='core.aiportfoliorecommendation')),
    ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
    ],
    options={
    'unique_together': {('portfolio_recommendation', 'stock')},
    },
    ),
    ]
