# Generated by Django 4.2.1 on 2025-09-20 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_crypto_models'),
        ('core', '0024_add_ticker_follow_model'),
    ]

    operations = [
    ]
