# Generated by Django 5.2.5 on 2025-09-02 01:35
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_aiportfoliorecommendation_incomeprofile_and_more'),
]
    operations = [
        migrations.AlterModelOptions(
        name='portfolio',
        options={'ordering': ['-updated_at']},
),
        migrations.RenameField(
model_name='portfolio',
old_name='description',
new_name='notes',
),
        migrations.AddField(
model_name='portfolio',
        name='stock',
field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.stock'),
),
        migrations.AddField(
model_name='portfolio',
        name='average_price',
field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
),
        migrations.AddField(
model_name='portfolio',
        name='shares',
field=models.IntegerField(default=0),
),
        migrations.AlterUniqueTogether(
        name='portfolio',
        unique_together={('user', 'stock')},
),
        migrations.RemoveField(
model_name='portfolio',
        name='is_public',
),
        migrations.RemoveField(
model_name='portfolio',
        name='name',
),
]
