# Generated by Django 5.2.8 on 2025-11-21 15:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_bank_transaction_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPortfolioRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_profile",
                    models.CharField(
                        choices=[
                            ("Conservative", "Conservative"),
                            ("Moderate", "Moderate"),
                            ("Aggressive", "Aggressive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("portfolio_allocation", models.JSONField(default=dict)),
                ("recommended_stocks", models.JSONField(default=list)),
                ("expected_portfolio_return", models.FloatField(blank=True, null=True)),
                ("risk_assessment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BrokerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alpaca_account_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVAL_PENDING", "Approval Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("INFO_REQUIRED", "Information Required"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("approval_reason", models.TextField(blank=True, null=True)),
                ("suitability_flags", models.JSONField(blank=True, default=dict)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "buying_power",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "equity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "day_trading_buying_power",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("pattern_day_trader", models.BooleanField(default=False)),
                ("day_trade_count", models.IntegerField(default=0)),
                ("trading_blocked", models.BooleanField(default=False)),
                ("transfer_blocked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "broker_accounts",
            },
        ),
        migrations.CreateModel(
            name="BrokerActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_id", models.CharField(max_length=100, unique=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("FILL", "Fill"),
                            ("TRANS", "Transfer"),
                            ("DIV", "Dividend"),
                            ("FEE", "Fee"),
                            ("INT", "Interest"),
                            ("CSD", "Cash Settlement"),
                            ("CSW", "Cash Withdrawal"),
                            ("CSR", "Cash Receipt"),
                            ("JRN", "Journal"),
                            ("JNLC", "Journal (Cash)"),
                            ("JNLS", "Journal (Stock)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "net_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("symbol", models.CharField(blank=True, max_length=10, null=True)),
                ("qty", models.IntegerField(blank=True, null=True)),
                (
                    "per_share_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "broker_activities",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BrokerFunding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_link_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[("DEPOSIT", "Deposit"), ("WITHDRAWAL", "Withdrawal")],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "alpaca_transfer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ach_relationship_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("micro_deposit_verified", models.BooleanField(default=False)),
                ("settlement_date", models.DateField(blank=True, null=True)),
                ("estimated_settlement_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "broker_funding",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BrokerGuardrailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("symbol", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "notional",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("allowed", models.BooleanField(default=False)),
                ("reason", models.TextField()),
                ("checks_performed", models.JSONField(blank=True, default=dict)),
                ("user_context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "broker_guardrail_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BrokerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_order_id", models.CharField(max_length=100, unique=True)),
                (
                    "alpaca_order_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("LIMIT", "Limit"),
                            ("STOP", "Stop"),
                            ("STOP_LIMIT", "Stop Limit"),
                            ("TRAILING_STOP", "Trailing Stop"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "time_in_force",
                    models.CharField(
                        choices=[
                            ("DAY", "Day"),
                            ("GTC", "Good Till Canceled"),
                            ("OPG", "Opening"),
                            ("CLS", "Closing"),
                            ("IOC", "Immediate or Cancel"),
                            ("FOK", "Fill or Kill"),
                        ],
                        default="DAY",
                        max_length=3,
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "notional",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "limit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stop_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("PENDING_NEW", "Pending New"),
                            ("ACCEPTED", "Accepted"),
                            ("PARTIALLY_FILLED", "Partially Filled"),
                            ("FILLED", "Filled"),
                            ("DONE_FOR_DAY", "Done For Day"),
                            ("CANCELED", "Canceled"),
                            ("EXPIRED", "Expired"),
                            ("REPLACED", "Replaced"),
                            ("PENDING_CANCEL", "Pending Cancel"),
                            ("PENDING_REPLACE", "Pending Replace"),
                            ("REJECTED", "Rejected"),
                            ("STOPPED", "Stopped"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("filled_qty", models.IntegerField(default=0)),
                (
                    "filled_avg_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("guardrail_checks_passed", models.BooleanField(default=False)),
                ("guardrail_reject_reason", models.TextField(blank=True, null=True)),
                ("fills", models.JSONField(blank=True, default=list)),
                ("alpaca_response", models.JSONField(blank=True, default=dict)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "broker_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BrokerPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("qty", models.IntegerField(default=0)),
                (
                    "avg_entry_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "market_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cost_basis",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "unrealized_pl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "unrealized_plpc",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "broker_positions",
            },
        ),
        migrations.CreateModel(
            name="BrokerStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("STATEMENT", "Account Statement"),
                            ("TAX_1099", "1099 Tax Document"),
                            ("CONFIRM", "Trade Confirmation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "alpaca_document_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "document_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "broker_statements",
                "ordering": ["-period_end", "-year"],
            },
        ),
        migrations.CreateModel(
            name="DiscussionComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaperTradingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100000.00"), max_digits=15
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100000.00"), max_digits=15
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100000.00"), max_digits=15
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_pnl_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("total_trades", models.IntegerField(default=0)),
                ("winning_trades", models.IntegerField(default=0)),
                ("losing_trades", models.IntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paper Trading Account",
                "verbose_name_plural": "Paper Trading Accounts",
                "db_table": "paper_trading_accounts",
            },
        ),
        migrations.CreateModel(
            name="PaperTradingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("LIMIT", "Limit"),
                            ("STOP", "Stop"),
                            ("STOP_LIMIT", "Stop Limit"),
                        ],
                        default="MARKET",
                        max_length=10,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "limit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stop_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "filled_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("filled_quantity", models.IntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("FILLED", "Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paper Trading Order",
                "verbose_name_plural": "Paper Trading Orders",
                "db_table": "paper_trading_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaperTradingPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shares", models.IntegerField(default=0)),
                (
                    "average_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "cost_basis",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "market_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "unrealized_pnl_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paper Trading Position",
                "verbose_name_plural": "Paper Trading Positions",
                "db_table": "paper_trading_positions",
            },
        ),
        migrations.CreateModel(
            name="PaperTradingTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("side", models.CharField(max_length=4)),
                ("quantity", models.IntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "realized_pnl_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Paper Trading Trade",
                "verbose_name_plural": "Paper Trading Trades",
                "db_table": "paper_trading_trades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shares", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "average_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="StockDiscussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("discussion_type", models.CharField(default="general", max_length=20)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public - Everyone can see"),
                            ("followers", "Followers Only - Only followers can see"),
                        ],
                        default="followers",
                        max_length=10,
                    ),
                ),
                ("is_analysis", models.BooleanField(default=False)),
                ("analysis_data", models.TextField(blank=True, null=True)),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="creditaction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="creditcard",
            name="user",
        ),
        migrations.RemoveField(
            model_name="creditprojection",
            name="user",
        ),
        migrations.RemoveField(
            model_name="creditscore",
            name="user",
        ),
        migrations.RemoveField(
            model_name="familygroup",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="familymember",
            name="family_group",
        ),
        migrations.RemoveField(
            model_name="familyinvite",
            name="family_group",
        ),
        migrations.RemoveField(
            model_name="orbsyncevent",
            name="family_group",
        ),
        migrations.RemoveField(
            model_name="familyinvite",
            name="accepted_by",
        ),
        migrations.RemoveField(
            model_name="familyinvite",
            name="invited_by",
        ),
        migrations.RemoveField(
            model_name="familymember",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orbsyncevent",
            name="user",
        ),
        migrations.RenameIndex(
            model_name="bankaccount",
            new_name="bank_accoun_user_id_5b6c03_idx",
            old_name="core_bankacc_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="bankaccount",
            new_name="bank_accoun_user_id_87197c_idx",
            old_name="core_bankacc_user_id_2_idx",
        ),
        migrations.RenameIndex(
            model_name="bankprovideraccount",
            new_name="bank_provid_user_id_6e5985_idx",
            old_name="core_bankpr_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="banktransaction",
            new_name="bank_transa_user_id_7b05c9_idx",
            old_name="core_banktra_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="banktransaction",
            new_name="bank_transa_bank_ac_292669_idx",
            old_name="core_banktra_bank_acc_idx",
        ),
        migrations.RenameIndex(
            model_name="banktransaction",
            new_name="bank_transa_user_id_379591_idx",
            old_name="core_banktra_user_id_3_idx",
        ),
        migrations.RenameIndex(
            model_name="banktransaction",
            new_name="bank_transa_user_id_76ec09_idx",
            old_name="core_banktr_user_id_trans_idx",
        ),
        migrations.RenameIndex(
            model_name="banktransaction",
            new_name="bank_transa_user_id_89a44e_idx",
            old_name="core_banktr_user_id_type_idx",
        ),
        migrations.RenameIndex(
            model_name="sblocbank",
            new_name="sbloc_banks_is_acti_d7ecd1_idx",
            old_name="sbloc_banks_is_acti_priority_idx",
        ),
        migrations.RenameIndex(
            model_name="sblocsession",
            new_name="sbloc_sessi_user_id_fa3244_idx",
            old_name="sbloc_sessions_user_id_status_idx",
        ),
        migrations.RenameIndex(
            model_name="sblocsession",
            new_name="sbloc_sessi_session_a94f00_idx",
            old_name="sbloc_sessions_session_id_idx",
        ),
        migrations.RenameIndex(
            model_name="stockmoment",
            new_name="core_stockm_symbol_6c8276_idx",
            old_name="core_stockm_symbol_tim_idx",
        ),
        migrations.RemoveField(
            model_name="bankwebhookevent",
            name="processed_at",
        ),
        migrations.RemoveField(
            model_name="bankwebhookevent",
            name="signature",
        ),
        migrations.AddField(
            model_name="stock",
            name="current_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="target_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="bankwebhookevent",
            name="provider_account_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="bankwebhookevent",
            index=models.Index(
                fields=["provider_account_id", "-created_at"],
                name="bank_webhoo_provide_7b899c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankwebhookevent",
            index=models.Index(
                fields=["processed", "-created_at"],
                name="bank_webhoo_process_6336f4_idx",
            ),
        ),
        migrations.AddField(
            model_name="aiportfoliorecommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broker_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="brokeractivity",
            name="broker_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="core.brokeraccount",
            ),
        ),
        migrations.AddField(
            model_name="brokerfunding",
            name="broker_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_records",
                to="core.brokeraccount",
            ),
        ),
        migrations.AddField(
            model_name="brokerguardraillog",
            name="broker_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guardrail_logs",
                to="core.brokeraccount",
            ),
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="broker_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="core.brokeraccount",
            ),
        ),
        migrations.AddField(
            model_name="brokerposition",
            name="broker_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="core.brokeraccount",
            ),
        ),
        migrations.AddField(
            model_name="brokerstatement",
            name="broker_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statements",
                to="core.brokeraccount",
            ),
        ),
        migrations.AddField(
            model_name="discussioncomment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="core.discussioncomment",
            ),
        ),
        migrations.AddField(
            model_name="discussioncomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussion_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="papertradingaccount",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="papertradingorder",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="core.papertradingaccount",
            ),
        ),
        migrations.AddField(
            model_name="papertradingorder",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_orders",
                to="core.stock",
            ),
        ),
        migrations.AddField(
            model_name="papertradingposition",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="core.papertradingaccount",
            ),
        ),
        migrations.AddField(
            model_name="papertradingposition",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_positions",
                to="core.stock",
            ),
        ),
        migrations.AddField(
            model_name="papertradingtrade",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="core.papertradingaccount",
            ),
        ),
        migrations.AddField(
            model_name="papertradingtrade",
            name="buy_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buy_trades",
                to="core.papertradingorder",
            ),
        ),
        migrations.AddField(
            model_name="papertradingtrade",
            name="sell_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sell_trades",
                to="core.papertradingorder",
            ),
        ),
        migrations.AddField(
            model_name="papertradingtrade",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_trades",
                to="core.stock",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_holdings",
                to="core.stock",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockdiscussion",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussions",
                to="core.stock",
            ),
        ),
        migrations.AddField(
            model_name="stockdiscussion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discussioncomment",
            name="discussion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.stockdiscussion",
            ),
        ),
        migrations.DeleteModel(
            name="CreditAction",
        ),
        migrations.DeleteModel(
            name="CreditCard",
        ),
        migrations.DeleteModel(
            name="CreditProjection",
        ),
        migrations.DeleteModel(
            name="CreditScore",
        ),
        migrations.DeleteModel(
            name="FamilyGroup",
        ),
        migrations.DeleteModel(
            name="FamilyInvite",
        ),
        migrations.DeleteModel(
            name="FamilyMember",
        ),
        migrations.DeleteModel(
            name="OrbSyncEvent",
        ),
        migrations.AddIndex(
            model_name="brokeraccount",
            index=models.Index(
                fields=["user", "kyc_status"], name="broker_acco_user_id_3137c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokeraccount",
            index=models.Index(
                fields=["alpaca_account_id"], name="broker_acco_alpaca__e3d1d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokeractivity",
            index=models.Index(
                fields=["broker_account", "date"], name="broker_acti_broker__691147_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokeractivity",
            index=models.Index(
                fields=["activity_id"], name="broker_acti_activit_647563_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerguardraillog",
            index=models.Index(
                fields=["broker_account", "created_at"],
                name="broker_guar_broker__c5cef5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brokerguardraillog",
            index=models.Index(
                fields=["action", "allowed"], name="broker_guar_action_0adcd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerorder",
            index=models.Index(
                fields=["broker_account", "status"],
                name="broker_orde_broker__efd5eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="brokerorder",
            index=models.Index(
                fields=["client_order_id"], name="broker_orde_client__cfde3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerorder",
            index=models.Index(
                fields=["alpaca_order_id"], name="broker_orde_alpaca__19605b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerorder",
            index=models.Index(
                fields=["symbol", "created_at"], name="broker_orde_symbol_7ddaf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerposition",
            index=models.Index(
                fields=["broker_account"], name="broker_posi_broker__9b5e6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brokerposition",
            index=models.Index(fields=["symbol"], name="broker_posi_symbol_ebefa4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="brokerposition",
            unique_together={("broker_account", "symbol")},
        ),
        migrations.AddIndex(
            model_name="brokerstatement",
            index=models.Index(
                fields=["broker_account", "document_type", "year"],
                name="broker_stat_broker__7241f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="papertradingorder",
            index=models.Index(
                fields=["account", "status"], name="paper_tradi_account_a03c10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="papertradingorder",
            index=models.Index(
                fields=["stock", "status"], name="paper_tradi_stock_i_fe8d74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="papertradingorder",
            index=models.Index(
                fields=["created_at"], name="paper_tradi_created_0aec45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="papertradingposition",
            index=models.Index(
                fields=["account"], name="paper_tradi_account_cf230a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="papertradingposition",
            index=models.Index(fields=["stock"], name="paper_tradi_stock_i_f0feac_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="papertradingposition",
            unique_together={("account", "stock")},
        ),
        migrations.AddIndex(
            model_name="papertradingtrade",
            index=models.Index(
                fields=["account", "created_at"], name="paper_tradi_account_819a6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="papertradingtrade",
            index=models.Index(
                fields=["stock", "created_at"], name="paper_tradi_stock_i_4c4918_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="portfolio",
            unique_together={("user", "stock")},
        ),
    ]
