# Generated by Django 5.2.5 on 2025-11-23 03:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_aiportfoliorecommendation_brokeraccount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayTradingSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal_id",
                    models.UUIDField(default=None, editable=False, unique=True),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("SAFE", "Safe"), ("AGGRESSIVE", "Aggressive")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                (
                    "side",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=5
                    ),
                ),
                ("features", models.JSONField(default=dict)),
                ("score", models.DecimalField(decimal_places=4, max_digits=10)),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stop_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("target_prices", models.JSONField(default=list)),
                ("time_stop_minutes", models.IntegerField()),
                (
                    "atr_5m",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("suggested_size_shares", models.IntegerField(default=100)),
                (
                    "risk_per_trade_pct",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Day Trading Signal",
                "verbose_name_plural": "Day Trading Signals",
                "db_table": "day_trading_signals",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["generated_at", "mode"],
                        name="day_trading_generat_bc3fc7_idx",
                    ),
                    models.Index(
                        fields=["symbol", "generated_at"],
                        name="day_trading_symbol_4a226c_idx",
                    ),
                    models.Index(
                        fields=["mode", "score"], name="day_trading_mode_e33e91_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StrategyPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("SAFE", "Safe"), ("AGGRESSIVE", "Aggressive")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("ALL_TIME", "All Time"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField(db_index=True)),
                ("period_end", models.DateTimeField(db_index=True)),
                ("total_signals", models.IntegerField(default=0)),
                ("signals_evaluated", models.IntegerField(default=0)),
                ("winning_signals", models.IntegerField(default=0)),
                ("losing_signals", models.IntegerField(default=0)),
                ("breakeven_signals", models.IntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "total_pnl_dollars",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_pnl_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "avg_pnl_per_signal",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("max_drawdown_duration_days", models.IntegerField(null=True)),
                (
                    "sortino_ratio",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "calmar_ratio",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "worst_single_loss",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "best_single_win",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("equity_curve", models.JSONField(blank=True, default=list)),
                (
                    "calculated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Strategy Performance",
                "verbose_name_plural": "Strategy Performances",
                "db_table": "strategy_performance",
                "ordering": ["-period_end", "-mode"],
                "indexes": [
                    models.Index(
                        fields=["mode", "period", "period_end"],
                        name="strategy_pe_mode_edbf5f_idx",
                    ),
                    models.Index(
                        fields=["calculated_at"], name="strategy_pe_calcula_e1895c_idx"
                    ),
                ],
                "unique_together": {("mode", "period", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="UserRiskBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "max_daily_risk_pct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("2.00"), max_digits=5
                    ),
                ),
                (
                    "daily_risk_used_pct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "daily_risk_reset_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "max_weekly_risk_pct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("5.00"), max_digits=5
                    ),
                ),
                (
                    "weekly_risk_used_pct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "weekly_risk_reset_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "max_daily_loss_pct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("3.00"), max_digits=5
                    ),
                ),
                (
                    "daily_pnl_pct",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("trading_paused", models.BooleanField(default=False)),
                ("trading_paused_until", models.DateTimeField(blank=True, null=True)),
                ("pause_reason", models.TextField(blank=True)),
                (
                    "max_position_size_pct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("10.00"), max_digits=5
                    ),
                ),
                (
                    "min_position_size_pct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                ("use_volatility_sizing", models.BooleanField(default=True)),
                ("volatility_lookback_days", models.IntegerField(default=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_budget",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Risk Budget",
                "verbose_name_plural": "User Risk Budgets",
                "db_table": "user_risk_budgets",
            },
        ),
        migrations.CreateModel(
            name="SignalPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horizon",
                    models.CharField(
                        choices=[
                            ("30m", "30 Minutes"),
                            ("2h", "2 Hours"),
                            ("EOD", "End of Day"),
                            ("1d", "1 Day"),
                            ("2d", "2 Days"),
                        ],
                        db_index=True,
                        max_length=5,
                    ),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "price_at_horizon",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("pnl_dollars", models.DecimalField(decimal_places=2, max_digits=15)),
                ("pnl_percent", models.DecimalField(decimal_places=4, max_digits=10)),
                ("hit_stop", models.BooleanField(default=False)),
                ("hit_target_1", models.BooleanField(default=False)),
                ("hit_target_2", models.BooleanField(default=False)),
                ("hit_time_stop", models.BooleanField(default=False)),
                ("outcome", models.CharField(max_length=20)),
                (
                    "max_favorable_excursion",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "max_adverse_excursion",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="core.daytradingsignal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signal Performance",
                "verbose_name_plural": "Signal Performances",
                "db_table": "signal_performance",
                "ordering": ["-evaluated_at"],
                "indexes": [
                    models.Index(
                        fields=["signal", "horizon"],
                        name="signal_perf_signal__18b90b_idx",
                    ),
                    models.Index(
                        fields=["horizon", "outcome"],
                        name="signal_perf_horizon_15f3dd_idx",
                    ),
                    models.Index(
                        fields=["evaluated_at"], name="signal_perf_evaluat_2d818e_idx"
                    ),
                ],
                "unique_together": {("signal", "horizon")},
            },
        ),
    ]
