# Generated by Django 5.2.5 on 2025-11-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_daytradingsignal_strategyperformance_userriskbudget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="daytradingsignal",
            name="universe_source",
            field=models.CharField(
                choices=[
                    ("CORE", "Core Universe"),
                    ("DYNAMIC_MOVERS", "Dynamic Movers"),
                ],
                db_index=True,
                default="CORE",
                help_text="Source of the stock universe (CORE = static, DYNAMIC_MOVERS = Polygon top movers)",
                max_length=20,
            ),
        ),
    ]
