# Generated by Django 5.2.8 on 2025-11-23 13:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_daytradingsignal_universe_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signalperformance",
            name="horizon",
            field=models.CharField(
                choices=[
                    ("30m", "30 Minutes"),
                    ("2h", "2 Hours"),
                    ("EOD", "End of Day"),
                    ("1d", "1 Day"),
                    ("2d", "2 Days"),
                    ("3d", "3 Days"),
                    ("5d", "5 Days"),
                    ("7d", "7 Days"),
                ],
                db_index=True,
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="signalperformance",
            name="signal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance",
                to="core.daytradingsignal",
            ),
        ),
        migrations.CreateModel(
            name="SwingTradingSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal_id",
                    models.UUIDField(default=None, editable=False, unique=True),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("MOMENTUM", "Swing Momentum"),
                            ("BREAKOUT", "Swing Breakout"),
                            ("MEAN_REVERSION", "Swing Mean Reversion"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "universe_source",
                    models.CharField(
                        choices=[
                            ("CORE", "Core Universe"),
                            ("DYNAMIC_MOVERS", "Dynamic Movers"),
                            ("ETF", "ETF Universe"),
                        ],
                        db_index=True,
                        default="CORE",
                        max_length=20,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                (
                    "side",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=5
                    ),
                ),
                ("features", models.JSONField(default=dict)),
                ("score", models.DecimalField(decimal_places=4, max_digits=10)),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stop_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("target_prices", models.JSONField(default=list)),
                ("hold_days", models.IntegerField(default=3)),
                (
                    "atr_1d",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("suggested_size_shares", models.IntegerField(default=100)),
                (
                    "risk_per_trade_pct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Swing Trading Signal",
                "verbose_name_plural": "Swing Trading Signals",
                "db_table": "swing_trading_signals",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["generated_at", "strategy"],
                        name="swing_tradi_generat_a6953c_idx",
                    ),
                    models.Index(
                        fields=["symbol", "generated_at"],
                        name="swing_tradi_symbol_adeb04_idx",
                    ),
                    models.Index(
                        fields=["strategy", "score"],
                        name="swing_tradi_strateg_67fa5b_idx",
                    ),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="signalperformance",
            unique_together={("signal", "horizon")},
        ),
        migrations.AddField(
            model_name="signalperformance",
            name="swing_signal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance",
                to="core.swingtradingsignal",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="signalperformance",
            unique_together={("signal", "horizon"), ("swing_signal", "horizon")},
        ),
    ]
