# Generated by Django 5.2.8 on 2025-11-30 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_signalperformance_horizon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionsAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                (
                    "strike",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("expiration", models.CharField(blank=True, max_length=20, null=True)),
                ("option_type", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("PRICE", "Price"),
                            ("IV", "Implied Volatility"),
                            ("EXPIRATION", "Expiration"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("direction", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TRIGGERED", "Triggered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("notification_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "options_alerts",
            },
        ),
        migrations.CreateModel(
            name="OptionsAlertNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_type", models.CharField(max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField()),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.optionsalert",
                    ),
                ),
            ],
            options={
                "db_table": "options_alert_notifications",
            },
        ),
        migrations.AddIndex(
            model_name="optionsalert",
            index=models.Index(
                fields=["user", "status"], name="options_ale_user_id_b366fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optionsalert",
            index=models.Index(
                fields=["symbol", "status"], name="options_ale_symbol_a4a55a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optionsalert",
            index=models.Index(
                fields=["alert_type", "status"], name="options_ale_alert_t_53696c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optionsalertnotification",
            index=models.Index(
                fields=["alert", "sent_at"], name="options_ale_alert_i_e9c74a_idx"
            ),
        ),
    ]
