# Generated by Django 5.2.8 on 2025-12-06 14:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_optionsalert_optionsalertnotification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MOMENTUM", "Momentum"),
                            ("REVERSAL", "Reversal"),
                            ("SWING", "Swing"),
                            ("FUTURES", "Futures"),
                            ("FOREX", "Forex"),
                            ("CRYPTO", "Crypto"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "influencer_ref",
                    models.CharField(
                        blank=True,
                        help_text="Internal reference to influencer (e.g., 'pj_trades', 'ross_cameron')",
                        max_length=50,
                    ),
                ),
                (
                    "market_type",
                    models.CharField(
                        choices=[
                            ("STOCKS", "Stocks"),
                            ("FUTURES", "Futures"),
                            ("FOREX", "Forex"),
                            ("CRYPTO", "Crypto"),
                            ("OPTIONS", "Options"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "timeframe_supported",
                    models.JSONField(
                        default=list,
                        help_text="List of supported timeframes: ['1m', '5m', '15m', '1h']",
                    ),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "RAHA Strategy",
                "verbose_name_plural": "RAHA Strategies",
                "db_table": "raha_strategies",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="StrategyVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "config_schema",
                    models.JSONField(
                        default=dict,
                        help_text="JSON schema defining strategy parameters and allowed ranges",
                    ),
                ),
                (
                    "logic_ref",
                    models.CharField(
                        help_text="Reference to implementation (e.g., 'ORB_v1', 'MOMENTUM_BREAKOUT_v1')",
                        max_length=100,
                    ),
                ),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy Version",
                "verbose_name_plural": "Strategy Versions",
                "db_table": "raha_strategy_versions",
                "ordering": ["strategy", "-version"],
                "unique_together": {("strategy", "version")},
            },
        ),
        migrations.CreateModel(
            name="RAHASignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("timeframe", models.CharField(default="5m", max_length=10)),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("ENTRY_LONG", "Entry Long"),
                            ("ENTRY_SHORT", "Entry Short"),
                            ("EXIT", "Exit"),
                            ("TAKE_PROFIT", "Take Profit"),
                            ("STOP_LOSS", "Stop Loss"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.5"),
                        help_text="ML confidence score (0-1)",
                        max_digits=5,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Additional signal metadata (candle pattern, ORB range, zone info, etc.)",
                    ),
                ),
                (
                    "day_trading_signal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to DayTradingSignal if this was generated from day trading engine",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raha_signals",
                        to="core.daytradingsignal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for global signals, set for personalized signals",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raha_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strategy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="core.strategyversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAHA Signal",
                "verbose_name_plural": "RAHA Signals",
                "db_table": "raha_signals",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "strategy_version"],
                        name="raha_signal_timesta_bb2499_idx",
                    ),
                    models.Index(
                        fields=["symbol", "timestamp"],
                        name="raha_signal_symbol_2131ed_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="raha_signal_user_id_7f89df_idx",
                    ),
                    models.Index(
                        fields=["strategy_version", "signal_type"],
                        name="raha_signal_strateg_650647_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RAHABacktestRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                ("timeframe", models.CharField(default="5m", max_length=10)),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Parameters used for this backtest"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Performance metrics: {win_rate, sharpe, max_drawdown, expectancy, etc.}",
                        null=True,
                    ),
                ),
                (
                    "equity_curve",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of {timestamp, equity} points",
                        null=True,
                    ),
                ),
                (
                    "trade_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of executed trades",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raha_backtests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strategy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtests",
                        to="core.strategyversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAHA Backtest Run",
                "verbose_name_plural": "RAHA Backtest Runs",
                "db_table": "raha_backtest_runs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="raha_backte_user_id_da7524_idx"
                    ),
                    models.Index(
                        fields=["strategy_version", "status"],
                        name="raha_backte_strateg_1c9f1e_idx",
                    ),
                    models.Index(
                        fields=["symbol", "start_date", "end_date"],
                        name="raha_backte_symbol_bd8f1f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserStrategySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="User's parameter overrides (e.g., {'risk_per_trade': 0.01, 'orb_minutes': 15})",
                    ),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "auto_trade_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="If true, signals will auto-execute (requires risk limits)",
                    ),
                ),
                (
                    "max_daily_loss_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Daily loss limit (e.g., 2.0 for 2%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "max_concurrent_positions",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum concurrent positions for this strategy",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_settings",
                        to="core.strategyversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raha_strategy_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Strategy Settings",
                "verbose_name_plural": "User Strategy Settings",
                "db_table": "raha_user_strategy_settings",
                "indexes": [
                    models.Index(
                        fields=["user", "enabled"],
                        name="raha_user_s_user_id_38e887_idx",
                    ),
                    models.Index(
                        fields=["strategy_version", "enabled"],
                        name="raha_user_s_strateg_bd7abf_idx",
                    ),
                ],
                "unique_together": {("user", "strategy_version")},
            },
        ),
    ]
