# Generated by Django 5.2.8 on 2025-12-07 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_strategy_strategyversion_rahasignal_rahabacktestrun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this custom strategy (null for system strategies)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_strategies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="is_custom",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if this is a user-created custom strategy",
            ),
        ),
    ]
