# Generated by Django 5.2.8 on 2025-12-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_add_custom_strategy_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategyversion",
            name="custom_logic",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom strategy logic definition (for user-created strategies)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="strategyversion",
            name="logic_ref",
            field=models.CharField(
                help_text="Reference to implementation (e.g., 'ORB_v1', 'MOMENTUM_BREAKOUT_v1', 'CUSTOM_<uuid>')",
                max_length=100,
            ),
        ),
    ]
