# Generated by Django 5.2.8 on 2025-12-07 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_add_custom_logic_to_strategy_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional: Model trained for specific symbol",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("confidence_predictor", "Confidence Predictor"),
                            ("win_probability", "Win Probability"),
                            ("pnl_predictor", "P&L Predictor"),
                        ],
                        default="confidence_predictor",
                        max_length=50,
                    ),
                ),
                (
                    "lookback_days",
                    models.IntegerField(
                        default=90, help_text="Days of data used for training"
                    ),
                ),
                (
                    "training_samples",
                    models.IntegerField(
                        default=0, help_text="Number of samples used for training"
                    ),
                ),
                (
                    "model_data",
                    models.TextField(help_text="Serialized model data (pickle/JSON)"),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Training metrics (accuracy, precision, recall, etc.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this model is currently being used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
                (
                    "strategy_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Model trained for specific strategy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_models",
                        to="core.strategyversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ML Model",
                "verbose_name_plural": "ML Models",
                "db_table": "raha_ml_models",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="raha_ml_mod_user_id_d7f895_idx",
                    ),
                    models.Index(
                        fields=["strategy_version", "is_active"],
                        name="raha_ml_mod_strateg_7ac706_idx",
                    ),
                    models.Index(
                        fields=["symbol", "model_type"],
                        name="raha_ml_mod_symbol_671fbd_idx",
                    ),
                ],
            },
        ),
    ]
