# Generated by Django 5.2.8 on 2025-12-07 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_add_ml_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyBlend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly name for this blend", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the blend"
                    ),
                ),
                (
                    "components",
                    models.JSONField(
                        default=list,
                        help_text="List of {strategy_version_id, weight} objects. Weights are normalized to sum to 1.0",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this blend is currently active for signal generation",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is the default blend for the user (only one default per user)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_blends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy Blend",
                "verbose_name_plural": "Strategy Blends",
                "db_table": "raha_strategy_blends",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="raha_strate_user_id_909d05_idx",
                    ),
                    models.Index(
                        fields=["user", "is_default"],
                        name="raha_strate_user_id_14b128_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("user", "is_default"),
                        name="unique_default_blend_per_user",
                    )
                ],
            },
        ),
    ]
