# Generated by Django 5.2.8 on 2025-12-07 15:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_add_strategy_blend"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "push_token",
                    models.TextField(
                        blank=True, help_text="Expo push notification token", null=True
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether push notifications are enabled",
                    ),
                ),
                (
                    "signal_notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable notifications for new RAHA signals",
                    ),
                ),
                (
                    "signal_confidence_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.70"),
                        help_text="Minimum confidence score to trigger notification (0.00-1.00)",
                        max_digits=3,
                    ),
                ),
                (
                    "signal_symbols",
                    models.JSONField(
                        default=list,
                        help_text="List of symbols to receive notifications for (empty = all symbols)",
                    ),
                ),
                (
                    "backtest_notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable notifications for backtest completion",
                    ),
                ),
                (
                    "backtest_success_only",
                    models.BooleanField(
                        default=False,
                        help_text="Only notify for successful backtests (win rate > 50%)",
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(default=False, help_text="Enable quiet hours"),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start of quiet hours (e.g., 22:00)",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True,
                        help_text="End of quiet hours (e.g., 08:00)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raha_notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RAHA Notification Preferences",
                "verbose_name_plural": "RAHA Notification Preferences",
                "db_table": "raha_notification_preferences",
            },
        ),
    ]
