# Generated by Django 5.2.8 on 2025-12-07 16:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_add_notification_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokerorder",
            name="raha_signal",
            field=models.ForeignKey(
                blank=True,
                help_text="RAHA signal that triggered this order (if auto-traded)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="broker_orders",
                to="core.rahasignal",
            ),
        ),
        migrations.AddField(
            model_name="brokerorder",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Order source: 'MANUAL', 'RAHA_AUTO', etc.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AutoTradingSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Enable/disable auto-trading for all strategies",
                    ),
                ),
                (
                    "min_confidence_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.75"),
                        help_text="Minimum confidence score to auto-execute (0.00-1.00)",
                        max_digits=3,
                    ),
                ),
                (
                    "position_sizing_method",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Dollar Amount"),
                            ("PERCENTAGE", "Percentage of Equity"),
                            ("RISK_BASED", "Risk-Based (R-Multiple)"),
                        ],
                        default="PERCENTAGE",
                        help_text="Method for calculating position size",
                        max_length=20,
                    ),
                ),
                (
                    "fixed_position_size",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        help_text="Fixed position size in dollars (for FIXED method)",
                        max_digits=10,
                    ),
                ),
                (
                    "position_size_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Position size as percentage of account equity (for PERCENTAGE method)",
                        max_digits=5,
                    ),
                ),
                (
                    "risk_per_trade_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Risk per trade as percentage of equity (for RISK_BASED method)",
                        max_digits=5,
                    ),
                ),
                (
                    "max_position_size_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Maximum position size as percentage of equity",
                        max_digits=5,
                    ),
                ),
                (
                    "max_daily_loss_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Maximum daily loss percentage before auto-trading stops (0 = disabled)",
                        max_digits=5,
                    ),
                ),
                (
                    "max_concurrent_positions",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum number of concurrent positions (0 = unlimited)",
                    ),
                ),
                (
                    "only_trade_market_hours",
                    models.BooleanField(
                        default=True,
                        help_text="Only execute trades during market hours (9:30 AM - 4:00 PM ET)",
                    ),
                ),
                (
                    "allowed_symbols",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of symbols allowed for auto-trading (empty = all symbols)",
                    ),
                ),
                (
                    "blocked_symbols",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of symbols blocked from auto-trading",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raha_auto_trading_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RAHA Auto-Trading Settings",
                "verbose_name_plural": "RAHA Auto-Trading Settings",
                "db_table": "raha_auto_trading_settings",
            },
        ),
    ]
