# Generated by Django 5.2.8 on 2025-12-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_add_raha_performance_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autotradingsettings",
            name="user",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="strategy_version",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notificationpreferences",
            name="user",
        ),
        migrations.RemoveField(
            model_name="strategyblend",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="rahabacktestrun",
            name="raha_backtest_user_strategy_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="rahabacktestrun",
            name="raha_backtest_user_status_completed_idx",
        ),
        migrations.RemoveIndex(
            model_name="rahasignal",
            name="raha_signal_user_symbol_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="rahasignal",
            name="raha_signal_user_strategy_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="rahasignal",
            name="raha_signal_symbol_timeframe_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="signalperformance",
            name="signal_perf_signal_evaluated_idx",
        ),
        migrations.RemoveIndex(
            model_name="signalperformance",
            name="signal_perf_outcome_evaluated_idx",
        ),
        migrations.RemoveField(
            model_name="brokerorder",
            name="raha_signal",
        ),
        migrations.RemoveField(
            model_name="brokerorder",
            name="source",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="is_custom",
        ),
        migrations.RemoveField(
            model_name="strategyversion",
            name="custom_logic",
        ),
        migrations.AlterField(
            model_name="strategyversion",
            name="logic_ref",
            field=models.CharField(
                help_text="Reference to implementation (e.g., 'ORB_v1', 'MOMENTUM_BREAKOUT_v1')",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="AutoTradingSettings",
        ),
        migrations.DeleteModel(
            name="MLModel",
        ),
        migrations.DeleteModel(
            name="NotificationPreferences",
        ),
        migrations.DeleteModel(
            name="StrategyBlend",
        ),
    ]
