# Generated by Django 5.2.8 on 2025-12-19 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_remove_autotradingsettings_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("SOC2", "SOC 2 Type II"),
                            ("PCI_DSS", "PCI DSS"),
                            ("GDPR", "GDPR"),
                            ("CCPA", "CCPA"),
                            ("HIPAA", "HIPAA"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("status", models.CharField(default="Compliant", max_length=50)),
                ("score", models.IntegerField(default=0)),
                ("last_audit_date", models.DateField(blank=True, null=True)),
                ("next_audit_date", models.DateField(blank=True, null=True)),
                ("audit_report_url", models.URLField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["standard"],
            },
        ),
        migrations.CreateModel(
            name="BiometricSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("face_id_enabled", models.BooleanField(default=False)),
                ("voice_id_enabled", models.BooleanField(default=False)),
                ("behavioral_id_enabled", models.BooleanField(default=True)),
                ("device_fingerprint_enabled", models.BooleanField(default=True)),
                ("location_tracking_enabled", models.BooleanField(default=False)),
                ("face_id_data", models.TextField(blank=True)),
                ("voice_id_data", models.TextField(blank=True)),
                ("device_fingerprint", models.CharField(blank=True, max_length=255)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("suspicious_login", "Suspicious Login"),
                            ("fraud_detection", "Fraud Detection"),
                            ("biometric_failure", "Biometric Failure"),
                            ("unusual_activity", "Unusual Activity"),
                            ("device_change", "Device Change"),
                            ("location_change", "Location Change"),
                            ("password_breach", "Password Breach"),
                            ("api_abuse", "API Abuse"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_securi_user_id_3e66ce_idx",
                    ),
                    models.Index(
                        fields=["threat_level", "resolved"],
                        name="core_securi_threat__475a8a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("factors", models.JSONField(default=dict)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-calculated_at"],
                        name="core_securi_user_id_b43182_idx",
                    )
                ],
            },
        ),
    ]
