# Generated by Django 5.2.8 on 2025-12-19 03:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_compliancestatus_biometricsettings_securityevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceAutomation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("SOC2", "SOC 2"),
                            ("ISO27001", "ISO 27001"),
                            ("PCI-DSS", "PCI-DSS"),
                            ("GDPR", "GDPR"),
                            ("CCPA", "CCPA"),
                            ("HIPAA", "HIPAA"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("automated", "Automated"),
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="automated",
                        max_length=20,
                    ),
                ),
                ("check_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warning", "Warning"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["standard", "check_name"],
                "indexes": [
                    models.Index(
                        fields=["standard", "status"],
                        name="core_compli_standar_c1fa14_idx",
                    ),
                    models.Index(
                        fields=["next_run"], name="core_compli_next_ru_71506e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplyChainVendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("payment_processor", "Payment Processor"),
                            ("data_provider", "Data Provider"),
                            ("cloud_provider", "Cloud Provider"),
                            ("security_service", "Security Service"),
                            ("ai_service", "AI Service"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("monitoring", "Under Monitoring"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("compliance_certifications", models.JSONField(default=list)),
                ("last_audit_date", models.DateTimeField(blank=True, null=True)),
                ("next_audit_date", models.DateTimeField(blank=True, null=True)),
                ("risk_score", models.IntegerField(default=50)),
                ("security_incidents", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-risk_score", "name"],
                "indexes": [
                    models.Index(
                        fields=["vendor_type", "status"],
                        name="core_supply_vendor__ab27dd_idx",
                    ),
                    models.Index(
                        fields=["risk_score"], name="core_supply_risk_sc_20413e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccessPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("resource", models.CharField(max_length=100)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("deny", "Deny"),
                            ("mfa_required", "MFA Required"),
                        ],
                        default="mfa_required",
                        max_length=20,
                    ),
                ),
                ("conditions", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "action", "resource"],
                        name="core_access_user_id_0c8110_idx",
                    )
                ],
                "unique_together": {("user", "action", "resource")},
            },
        ),
        migrations.CreateModel(
            name="DeviceTrust",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=255)),
                ("device_fingerprint", models.TextField()),
                ("trust_score", models.IntegerField(default=50)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_verified", models.DateTimeField(auto_now=True)),
                (
                    "last_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("is_trusted", models.BooleanField(default=False)),
                ("verification_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "device_id"],
                        name="core_device_user_id_d685c1_idx",
                    ),
                    models.Index(
                        fields=["user", "-trust_score"],
                        name="core_device_user_id_16cf3e_idx",
                    ),
                ],
                "unique_together": {("user", "device_id")},
            },
        ),
    ]
