# Generated by Django 5.2.8 on 2026-02-01 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_add_yodlee_loginname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailybriefcompletion",
            name="brief",
        ),
        migrations.RemoveField(
            model_name="dailybriefcompletion",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="userachievement",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userachievement",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprogress",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userstreak",
            name="user",
        ),
        migrations.CreateModel(
            name="SignalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("action", models.CharField(max_length=10)),
                ("confidence", models.FloatField()),
                ("entry_price", models.FloatField(blank=True, null=True)),
                (
                    "entry_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("exit_price", models.FloatField(blank=True, null=True)),
                ("exit_timestamp", models.DateTimeField(blank=True, null=True)),
                ("pnl", models.FloatField(blank=True, null=True)),
                ("pnl_percent", models.FloatField(blank=True, null=True)),
                ("reasoning", models.TextField(blank=True)),
                ("status", models.CharField(default="OPEN", max_length=20)),
                ("user_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "transparency_signals",
                "ordering": ["-entry_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "-entry_timestamp"],
                        name="transparenc_symbol_140105_idx",
                    ),
                    models.Index(
                        fields=["status", "-entry_timestamp"],
                        name="transparenc_status_4749f7_idx",
                    ),
                ],
            },
        ),
        migrations.DeleteModel(
            name="DailyBrief",
        ),
        migrations.DeleteModel(
            name="DailyBriefCompletion",
        ),
        migrations.DeleteModel(
            name="UserAchievement",
        ),
        migrations.DeleteModel(
            name="UserProgress",
        ),
        migrations.DeleteModel(
            name="UserStreak",
        ),
    ]
