# Generated by Django 5.2.8 on 2026-02-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_remove_dailybriefcompletion_brief_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalrecord",
            name="signal_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="signalrecord",
            name="trading_mode",
            field=models.CharField(
                choices=[("PAPER", "Paper Trading"), ("LIVE", "Live Trading")],
                default="PAPER",
                max_length=20,
            ),
        ),
    ]
