# Generated by Django 5.2.8 on 2026-02-05 04:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_load_lesson_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionsRegimeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10, unique=True)),
                (
                    "regime",
                    models.CharField(
                        help_text="e.g., MEAN_REVERSION, TREND_UP, CRASH_PANIC",
                        max_length=30,
                    ),
                ),
                (
                    "regime_confidence",
                    models.CharField(
                        default="MEDIUM", help_text="HIGH, MEDIUM, LOW", max_length=10
                    ),
                ),
                (
                    "iv_rank",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="IV percentile (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "regime_description",
                    models.TextField(
                        blank=True, help_text="Human-readable regime context"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Options Regime Snapshot",
                "verbose_name_plural": "Options Regime Snapshots",
            },
        ),
        # Removed RemoveField/AlterUniqueTogether ops for DailyBriefCompletion,
        # UserAchievement, UserProgress, UserStreak — these tables are dropped
        # entirely by DeleteModel below, so RemoveField is redundant and
        # causes state inconsistency.
        migrations.CreateModel(
            name="OptionsPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_equity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total account value (cash + positions)",
                        max_digits=15,
                    ),
                ),
                (
                    "total_delta",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "total_vega",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "total_theta",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "total_gamma",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "total_risk_dollars",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of max_loss across all positions",
                        max_digits=15,
                    ),
                ),
                ("total_positions_count", models.IntegerField(default=0)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("pro", "Professional"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                (
                    "risk_appetite",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        help_text="Risk tolerance: 0.0 (conservative) to 1.0 (aggressive)",
                        max_digits=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options_portfolio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Options Portfolio",
                "verbose_name_plural": "Options Portfolios",
            },
        ),
        migrations.CreateModel(
            name="OptionsPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10)),
                (
                    "sector",
                    models.CharField(blank=True, default="Unknown", max_length=50),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        help_text="e.g., IRON_CONDOR, BULL_CALL_SPREAD, LONG_STRADDLE",
                        max_length=50,
                    ),
                ),
                (
                    "legs",
                    models.JSONField(
                        help_text="Array of legs: [{type: 'call', strike: 100, expiry: '2026-03-20', contracts: 2, side: 'buy'}]"
                    ),
                ),
                (
                    "contracts",
                    models.IntegerField(
                        default=1,
                        help_text="Number of spreads/straddles (multiply legs by this)",
                    ),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Net credit/debit at entry (positive = credit)",
                        max_digits=10,
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current mark price (updated via data feed)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "position_delta",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "position_vega",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "position_theta",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "position_gamma",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "max_profit",
                    models.DecimalField(
                        decimal_places=2, help_text="Max gain in dollars", max_digits=10
                    ),
                ),
                (
                    "max_loss",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Max loss in dollars (risk amount)",
                        max_digits=10,
                    ),
                ),
                (
                    "probability_of_profit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="PoP as percentage (e.g., 66.00 for 66%)",
                        max_digits=5,
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Locked-in profit/loss after close",
                        max_digits=15,
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current P&L (updated via mark price)",
                        max_digits=15,
                    ),
                ),
                (
                    "regime_at_entry",
                    models.CharField(
                        blank=True,
                        help_text="Market regime when trade was opened (e.g., MEAN_REVERSION)",
                        max_length=30,
                    ),
                ),
                (
                    "edge_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Router composite score at entry (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "flight_manual",
                    models.TextField(
                        blank=True,
                        help_text="JSON serialized FlightManual for reference",
                    ),
                ),
                ("is_closed", models.BooleanField(db_index=True, default=False)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="core.optionsportfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Options Position",
                "verbose_name_plural": "Options Positions",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.DeleteModel(
            name="DailyBrief",
        ),
        migrations.DeleteModel(
            name="DailyBriefCompletion",
        ),
        migrations.DeleteModel(
            name="UserAchievement",
        ),
        migrations.DeleteModel(
            name="UserProgress",
        ),
        migrations.DeleteModel(
            name="UserStreak",
        ),
    ]
