# Generated by Django 5.2.5 on 2026-02-06 15:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_options_edge_factory_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyHealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy_name",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("consecutive_passes", models.IntegerField(default=0)),
                ("last_backtest_date", models.DateField(blank=True, null=True)),
                ("last_backtest_passed", models.BooleanField(default=True)),
                ("auto_disabled", models.BooleanField(default=False)),
                ("auto_disabled_at", models.DateTimeField(blank=True, null=True)),
                ("last_optimization_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Strategy Health Record",
                "verbose_name_plural": "Strategy Health Records",
                "db_table": "strategy_health_records",
            },
        ),
        migrations.CreateModel(
            name="SymbolExecutionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10, unique=True)),
                (
                    "avg_slippage_bps",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "avg_quality_score",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("5.0"), max_digits=5
                    ),
                ),
                ("fill_count", models.IntegerField(default=0)),
                ("avg_time_to_fill_seconds", models.FloatField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Symbol Execution Profile",
                "verbose_name_plural": "Symbol Execution Profiles",
                "db_table": "symbol_execution_profiles",
            },
        ),
        migrations.CreateModel(
            name="UserFill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                ("side", models.CharField(max_length=5)),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("shares", models.IntegerField(default=100)),
                (
                    "pnl_dollars",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "pnl_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "slippage_bps",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "execution_quality_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WIN", "Win"),
                            ("LOSS", "Loss"),
                            ("BREAKEVEN", "Breakeven"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hit_stop", models.BooleanField(default=False)),
                ("hit_target", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_fills",
                        to="core.daytradingsignal",
                    ),
                ),
                (
                    "swing_signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_fills",
                        to="core.swingtradingsignal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Fill",
                "verbose_name_plural": "User Fills",
                "db_table": "user_fills",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="user_fills_user_id_0c9875_idx",
                    ),
                    models.Index(
                        fields=["signal", "user"], name="user_fills_signal__3731b0_idx"
                    ),
                    models.Index(
                        fields=["symbol", "created_at"],
                        name="user_fills_symbol_31ece9_idx",
                    ),
                ],
            },
        ),
    ]
