# Generated by Django 5.2.5 on 2026-02-06 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_strategyhealthrecord_symbolexecutionprofile_userfill"),
    ]

    operations = [
        migrations.CreateModel(
            name="BanditArm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy_slug",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("alpha", models.FloatField(default=1.0)),
                ("beta_param", models.FloatField(default=1.0)),
                ("total_pulls", models.IntegerField(default=0)),
                ("total_rewards", models.FloatField(default=0.0)),
                (
                    "context_alphas",
                    models.JSONField(
                        default=dict,
                        help_text='Regime-specific alpha values, e.g. {"TREND_UP": 5.0}',
                    ),
                ),
                (
                    "context_betas",
                    models.JSONField(
                        default=dict,
                        help_text='Regime-specific beta values, e.g. {"TREND_UP": 2.0}',
                    ),
                ),
                ("current_weight", models.FloatField(default=0.25)),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bandit Arm",
                "verbose_name_plural": "Bandit Arms",
                "db_table": "bandit_arms",
            },
        ),
        migrations.CreateModel(
            name="ParameterOptimizationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("strategy_name", models.CharField(db_index=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("parameter_space", models.JSONField(default=dict)),
                ("best_parameters", models.JSONField(default=dict)),
                ("best_objective_value", models.FloatField(blank=True, null=True)),
                ("n_trials", models.IntegerField(default=50)),
                ("all_trials", models.JSONField(default=list)),
                (
                    "triggered_by",
                    models.CharField(default="nightly_backtest", max_length=50),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Parameter Optimization Run",
                "verbose_name_plural": "Parameter Optimization Runs",
                "db_table": "parameter_optimization_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegimeThresholdSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                (
                    "thresholds",
                    models.JSONField(
                        default=dict,
                        help_text='Learned thresholds, e.g. {"rv_spike_threshold": 1.15, "price_crash_threshold": -0.035}',
                    ),
                ),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("sharpe_improvement", models.FloatField(blank=True, null=True)),
                ("optimization_run_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Regime Threshold Set",
                "verbose_name_plural": "Regime Threshold Sets",
                "db_table": "regime_threshold_sets",
                "ordering": ["-created_at"],
            },
        ),
    ]
