# Generated by Django 5.2.5 on 2026-02-06 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_banditarm_parameteroptimizationrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("q_table", "Q-Table"),
                            ("contextual_bandit", "Contextual Bandit"),
                        ],
                        default="q_table",
                        max_length=30,
                    ),
                ),
                (
                    "policy_data",
                    models.JSONField(
                        default=dict,
                        help_text='Serialized Q-table: {"state_key": {"action": q_value, ...}, ...}',
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("train_episodes", models.IntegerField(default=0)),
                ("avg_reward", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "execution_policies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HMMTrainingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                ("n_states", models.IntegerField(default=5)),
                ("log_likelihood", models.FloatField(blank=True, null=True)),
                ("bic", models.FloatField(blank=True, null=True)),
                ("aic", models.FloatField(blank=True, null=True)),
                (
                    "state_mapping",
                    models.JSONField(
                        default=dict,
                        help_text='Maps hidden state index to semantic label: {0: "CRASH", 1: "TREND_UP", ...}',
                    ),
                ),
                ("training_days", models.IntegerField(default=0)),
                ("model_path", models.CharField(max_length=300)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "hmm_training_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShadowModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("gradient_boosting", "Gradient Boosting"),
                            ("random_forest", "Random Forest"),
                            ("mlp", "MLP Neural Network"),
                        ],
                        max_length=30,
                    ),
                ),
                ("hyperparameters", models.JSONField(default=dict)),
                ("model_path", models.CharField(max_length=300)),
                ("scaler_path", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRAINING", "Training"),
                            ("VALIDATING", "Validating"),
                            ("PROMOTED", "Promoted"),
                            ("EXPIRED", "Expired"),
                            ("FAILED", "Failed"),
                        ],
                        default="TRAINING",
                        max_length=20,
                    ),
                ),
                ("train_score", models.FloatField(blank=True, null=True)),
                ("test_score", models.FloatField(blank=True, null=True)),
                ("validation_accuracy", models.FloatField(blank=True, null=True)),
                ("incumbent_accuracy", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validation_start", models.DateTimeField(blank=True, null=True)),
                ("validation_end", models.DateTimeField(blank=True, null=True)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Shadow Model",
                "db_table": "shadow_models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="banditarm",
            name="discount_rate",
            field=models.FloatField(
                default=0.995,
                help_text="Current adaptive discount rate (0.90 = aggressive forgetting, 0.995 = slow)",
            ),
        ),
        migrations.AddField(
            model_name="banditarm",
            name="regime_change_count",
            field=models.IntegerField(
                default=0, help_text="Recent regime changes (decayed over time)"
            ),
        ),
        migrations.AddField(
            model_name="banditarm",
            name="reward_history",
            field=models.JSONField(
                default=list,
                help_text="Sliding window of last 100 rewards [{reward, timestamp, regime}, ...]",
            ),
        ),
        migrations.CreateModel(
            name="HMMRegimeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                ("hmm_regime", models.CharField(max_length=30)),
                (
                    "hmm_probabilities",
                    models.JSONField(
                        default=dict,
                        help_text='Probability distribution: {"CRASH": 0.05, "TREND_UP": 0.70, ...}',
                    ),
                ),
                ("rule_regime", models.CharField(max_length=30)),
                ("ensemble_regime", models.CharField(max_length=30)),
                (
                    "transition_probs",
                    models.JSONField(
                        default=dict,
                        help_text="Transition probabilities from current state",
                    ),
                ),
                ("detected_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "hmm_regime_snapshots",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "detected_at"],
                        name="hmm_regime__symbol_cf0e44_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RegimeChangeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                ("previous_regime", models.CharField(max_length=30)),
                ("new_regime", models.CharField(max_length=30)),
                ("detected_at", models.DateTimeField(db_index=True)),
                ("confidence", models.FloatField(default=1.0)),
            ],
            options={
                "db_table": "regime_change_events",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["detected_at", "symbol"],
                        name="regime_chan_detecte_f25fbf_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutionExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state_features",
                    models.JSONField(
                        default=dict,
                        help_text="Discretized state: {spread_bps, volume_ratio, time_bucket, ...}",
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("MARKET_IMMEDIATE", "Market Immediate"),
                            ("LIMIT_TIGHT", "Limit Tight"),
                            ("LIMIT_LOOSE", "Limit Loose"),
                            ("WAIT_5MIN", "Wait 5 Minutes"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reward",
                    models.FloatField(
                        help_text="Negative slippage + quality bonus, bounded [-50, +10]"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_fill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rl_experience",
                        to="core.userfill",
                    ),
                ),
            ],
            options={
                "db_table": "execution_experiences",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="execution_e_created_2b1200_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShadowPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shadow_score", models.FloatField()),
                ("incumbent_score", models.FloatField()),
                ("actual_outcome", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shadow_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="core.shadowmodel",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadow_predictions",
                        to="core.daytradingsignal",
                    ),
                ),
            ],
            options={
                "db_table": "shadow_predictions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shadow_model", "created_at"],
                        name="shadow_pred_shadow__c3145b_idx",
                    )
                ],
            },
        ),
    ]
