# Generated by GitHub Copilot for local DeFi model tables
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0054_executionpolicy_hmmtrainingrecord_shadowmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeFiProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("logo_url", models.URLField(blank=True, default="", max_length=500)),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                ("audit_firms", models.JSONField(default=list)),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.5,
                        help_text="Protocol risk score 0.0 (lowest risk) to 1.0 (highest risk)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "defi_protocol",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeFiPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chain",
                    models.CharField(
                        choices=[
                            ("ethereum", "Ethereum"),
                            ("polygon", "Polygon"),
                            ("arbitrum", "Arbitrum"),
                            ("base", "Base"),
                            ("optimism", "Optimism"),
                            ("avalanche", "Avalanche"),
                        ],
                        max_length=50,
                    ),
                ),
                ("chain_id", models.IntegerField(help_text="EVM chain ID (1=Ethereum, 137=Polygon, etc.)")),
                ("symbol", models.CharField(help_text="Token symbol (e.g., USDC, ETH/USDC)", max_length=100)),
                ("pool_address", models.CharField(blank=True, default="", max_length=66)),
                (
                    "pool_type",
                    models.CharField(
                        choices=[
                            ("lending", "Lending"),
                            ("lp", "Liquidity Pool"),
                            ("staking", "Staking"),
                            ("vault", "Vault"),
                            ("yield", "Yield Farming"),
                        ],
                        default="lending",
                        max_length=30,
                    ),
                ),
                (
                    "defi_llama_pool_id",
                    models.CharField(
                        blank=True,
                        help_text="DefiLlama pool UUID for data syncing",
                        max_length=200,
                        null=True,
                        unique=True,
                    ),
                ),
                ("url", models.URLField(blank=True, default="", help_text="Pool page URL on protocol", max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pools",
                        to="core.defiprotocol",
                    ),
                ),
            ],
            options={
                "db_table": "defi_pool",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["chain", "is_active"], name="defi_pool_chain_is_active_idx"),
                    models.Index(fields=["protocol", "chain"], name="defi_pool_protocol_chain_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="YieldSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apy_base", models.FloatField(help_text="Base APY from protocol fees/interest")),
                ("apy_reward", models.FloatField(default=0, help_text="Additional APY from reward tokens")),
                ("apy_total", models.FloatField(help_text="Total APY (base + reward)")),
                ("tvl_usd", models.FloatField(help_text="Total value locked in USD")),
                (
                    "risk_score",
                    models.FloatField(default=0.5, help_text="Pool risk score 0.0-1.0"),
                ),
                (
                    "il_estimate",
                    models.FloatField(blank=True, help_text="Estimated impermanent loss percentage (for LP pools)", null=True),
                ),
                (
                    "volume_24h_usd",
                    models.FloatField(blank=True, help_text="24-hour trading volume in USD", null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yield_snapshots",
                        to="core.defipool",
                    ),
                ),
            ],
            options={
                "db_table": "defi_yield_snapshot",
                "ordering": ["-timestamp"],
                "get_latest_by": "timestamp",
                "indexes": [
                    models.Index(fields=["pool", "-timestamp"], name="defi_yield_pool_ts_idx"),
                    models.Index(fields=["-timestamp"], name="defi_yield_ts_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserDeFiPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(max_length=66)),
                (
                    "staked_amount",
                    models.DecimalField(decimal_places=18, help_text="Amount of tokens staked/deposited", max_digits=30),
                ),
                (
                    "staked_value_usd",
                    models.DecimalField(decimal_places=2, help_text="USD value at time of stake", max_digits=20),
                ),
                (
                    "rewards_earned",
                    models.DecimalField(decimal_places=18, default=0, help_text="Accumulated rewards", max_digits=30),
                ),
                (
                    "realized_apy",
                    models.FloatField(blank=True, help_text="Actual realized APY for this position", null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_positions",
                        to="core.defipool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defi_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "defi_user_position",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["user", "is_active"], name="defi_pos_user_active_idx"),
                    models.Index(fields=["wallet_address"], name="defi_pos_wallet_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeFiTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdraw", "Withdraw"),
                            ("harvest", "Harvest Rewards"),
                            ("approve", "Token Approval"),
                            ("borrow", "Borrow"),
                            ("repay", "Repay"),
                            ("swap", "Token Swap"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tx_hash", models.CharField(max_length=66, unique=True)),
                ("chain_id", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=18, max_digits=30)),
                ("amount_usd", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("gas_used", models.BigIntegerField(blank=True, null=True)),
                ("gas_price_gwei", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.defipool",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="core.userdefiposition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defi_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "defi_transaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="defi_tx_user_created_idx"),
                    models.Index(fields=["tx_hash"], name="defi_tx_hash_idx"),
                    models.Index(fields=["status"], name="defi_tx_status_idx"),
                ],
            },
        ),
    ]
