# Generated by Django 5.2.5 on 2025-08-30 23:43
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
    ('core', '0006_add_follow_model'),
    ]
    operations = [
    migrations.AddField(
    model_name='user',
    name='profile_pic',
    field=models.URLField(blank=True, max_length=500, null=True),
    ),
    ]
