"""
Enhanced Voice AI Configuration for RichesReach
"""

import os
from pathlib import Path

# Base directory
BASE_DIR = Path(__file__).resolve().parent

# TTS Configuration
TTS_CONFIG = {
    # Model settings
    'MODEL_NAME': 'tts_models/multilingual/multi-dataset/xtts_v2',
    'MODEL_PATH': BASE_DIR / 'models' / 'xtts_v2',
    
    # Audio settings
    'AUDIO_OUTPUT_DIR': BASE_DIR / 'media' / 'tts_audio',
    'AUDIO_FORMAT': 'wav',
    'SAMPLE_RATE': 22050,
    'BIT_DEPTH': 16,
    
    # Voice samples
    'VOICE_SAMPLES_DIR': BASE_DIR / 'voices',
    'DEFAULT_VOICE_SAMPLE': 'default_finance_voice.wav',
    
    # Natural speech parameters
    'NATURAL_SPEECH': {
        'USE_SPEAKER_EMBEDDING': True,
        'USE_GST': True,  # Global Style Tokens
        'TEMPERATURE_RANGE': (0.0, 1.0),
        'SPEED_RANGE': (0.5, 2.0),
        'EMOTION_WEIGHTS': {
            'neutral': 0.5,
            'confident': 0.8,
            'friendly': 0.7,
            'analytical': 0.6,
            'encouraging': 0.9,
        }
    },
    
    # Performance settings
    'MAX_BATCH_SIZE': 10,
    'AUDIO_CACHE_HOURS': 24,
    'CLEANUP_INTERVAL_HOURS': 6,
    
    # Quality settings
    'HIGH_QUALITY': True,
    'NOISE_REDUCTION': True,
    'NORMALIZE_AUDIO': True,
}

# Voice-specific configurations
VOICE_CONFIGS = {
    'default': {
        'name': 'Default Finance Voice',
        'description': 'Professional, neutral tone for general finance content',
        'temperature': 0.7,
        'length_penalty': 1.0,
        'repetition_penalty': 1.1,
        'top_k': 50,
        'top_p': 0.9,
        'num_beams': 4,
        'emotions': ['neutral', 'confident'],
    },
    'finance_expert': {
        'name': 'Finance Expert',
        'description': 'Authoritative voice for market analysis and insights',
        'temperature': 0.6,
        'length_penalty': 1.1,
        'repetition_penalty': 1.05,
        'top_k': 40,
        'top_p': 0.85,
        'num_beams': 6,
        'emotions': ['confident', 'analytical'],
    },
    'friendly_advisor': {
        'name': 'Friendly Advisor',
        'description': 'Warm, approachable voice for personal finance advice',
        'temperature': 0.8,
        'length_penalty': 0.9,
        'repetition_penalty': 1.15,
        'top_k': 60,
        'top_p': 0.95,
        'num_beams': 3,
        'emotions': ['friendly', 'encouraging'],
    },
    'confident_analyst': {
        'name': 'Confident Analyst',
        'description': 'Strong, decisive voice for trading recommendations',
        'temperature': 0.5,
        'length_penalty': 1.2,
        'repetition_penalty': 1.0,
        'top_k': 30,
        'top_p': 0.8,
        'num_beams': 8,
        'emotions': ['confident', 'analytical'],
    }
}

# Finance terminology pronunciation dictionary
FINANCE_PRONUNCIATIONS = {
    # Basic terms
    'portfolio': 'port-folio',
    'yield': 'yield',
    'dividend': 'div-i-dend',
    'volatility': 'vol-a-til-ity',
    'diversification': 'di-ver-si-fi-ca-tion',
    'liquidity': 'li-quid-ity',
    'leverage': 'lev-er-age',
    'equity': 'eq-ui-ty',
    'bond': 'bond',
    'stock': 'stock',
    'share': 'share',
    'market': 'mar-ket',
    'trading': 'trad-ing',
    'investment': 'in-vest-ment',
    'return': 're-turn',
    'profit': 'prof-it',
    'loss': 'loss',
    'gain': 'gain',
    'risk': 'risk',
    'asset': 'as-set',
    'liability': 'li-a-bil-ity',
    'revenue': 'rev-e-nue',
    'expense': 'ex-pense',
    'income': 'in-come',
    'capital': 'cap-i-tal',
    'interest': 'in-ter-est',
    'principal': 'prin-ci-pal',
    'maturity': 'ma-tur-ity',
    'coupon': 'cou-pon',
    'premium': 'pre-mi-um',
    'discount': 'dis-count',
    'spread': 'spread',
    'margin': 'mar-gin',
    'collateral': 'col-lat-er-al',
    'derivative': 'de-riv-a-tive',
    'futures': 'fu-tures',
    'options': 'op-tions',
    'hedge': 'hedge',
    'arbitrage': 'ar-bi-trage',
    'speculation': 'spec-u-la-tion',
    'analysis': 'a-nal-y-sis',
    'valuation': 'val-u-a-tion',
    'earnings': 'earn-ings',
    'cash flow': 'cash flow',
    'balance sheet': 'bal-ance sheet',
    'income statement': 'in-come state-ment',
    'P&L': 'P-and-L',
    'EBITDA': 'E-B-I-T-D-A',
    'EPS': 'E-P-S',
    'P/E ratio': 'P-E ra-tio',
    'ROI': 'R-O-I',
    'ROE': 'R-O-E',
    'ROA': 'R-O-A',
    'APY': 'A-P-Y',
    'APR': 'A-P-R',
    'CD': 'C-D',
    'IRA': 'I-R-A',
    '401k': 'four-oh-one-k',
    '403b': 'four-oh-three-b',
    'Roth': 'Roth',
    'Traditional': 'Tra-di-tion-al',
    'ETF': 'E-T-F',
    'mutual fund': 'mu-tu-al fund',
    'index fund': 'in-dex fund',
    'hedge fund': 'hedge fund',
    'private equity': 'pri-vate eq-ui-ty',
    'venture capital': 'ven-ture cap-i-tal',
    'IPO': 'I-P-O',
    'M&A': 'M-and-A',
    'merger': 'mer-ger',
    'acquisition': 'ac-qui-si-tion',
    'spin-off': 'spin-off',
    'stock split': 'stock split',
    'buyback': 'buy-back',
    'shareholder': 'share-hold-er',
    'stakeholder': 'stake-hold-er',
    'board': 'board',
    'CEO': 'C-E-O',
    'CFO': 'C-F-O',
    'CTO': 'C-T-O',
    'COO': 'C-O-O',
    'NASDAQ': 'NAS-DAQ',
    'NYSE': 'N-Y-S-E',
    'S&P 500': 'S-and-P five-hundred',
    'Dow Jones': 'Dow Jones',
    'Russell 2000': 'Rus-sell two-thou-sand',
    'Federal Reserve': 'Fed-er-al Re-serve',
    'Fed': 'Fed',
    'FOMC': 'F-O-M-C',
    'inflation': 'in-fla-tion',
    'deflation': 'de-fla-tion',
    'stagflation': 'stag-fla-tion',
    'recession': 're-ces-sion',
    'depression': 'de-pres-sion',
    'recovery': 're-cov-er-y',
    'expansion': 'ex-pan-sion',
    'contraction': 'con-trac-tion',
    'bull market': 'bull mar-ket',
    'bear market': 'bear mar-ket',
    'correction': 'cor-rec-tion',
    'crash': 'crash',
    'rally': 'ral-ly',
    'VIX': 'V-I-X',
    'beta': 'be-ta',
    'alpha': 'al-pha',
    'gamma': 'gam-ma',
    'delta': 'del-ta',
    'theta': 'the-ta',
    'vega': 've-ga',
    'rho': 'rho',
    'Sharpe ratio': 'Sharpe ra-tio',
    'Sortino ratio': 'Sor-ti-no ra-tio',
    'Jensen\'s alpha': 'Jen-sen\'s al-pha',
    'Treynor ratio': 'Trey-nor ra-tio',
    'Information ratio': 'In-for-ma-tion ra-tio',
    'Calmar ratio': 'Cal-mar ra-tio',
    'Sterling ratio': 'Ster-ling ra-tio',
    'Burke ratio': 'Burke ra-tio',
    'Kappa ratio': 'Kap-pa ra-tio',
    'Omega ratio': 'O-me-ga ra-tio',
    'Gain-to-Pain ratio': 'Gain-to-Pain ra-tio',
    'Ulcer Index': 'Ul-cer In-dex',
    'Maximum Drawdown': 'Max-i-mum Draw-down',
    'Value at Risk': 'Val-ue at Risk',
    'VaR': 'V-a-R',
    'Expected Shortfall': 'Ex-pect-ed Short-fall',
    'Conditional Value at Risk': 'Con-di-tion-al Val-ue at Risk',
    'CVaR': 'C-V-a-R',
    'Monte Carlo': 'Mon-te Car-lo',
    'Black-Scholes': 'Black-Scho-les',
    'Binomial': 'Bi-no-mi-al',
    'trinomial': 'tri-no-mi-al',
    'lattice': 'lat-tice',
    'finite difference': 'fi-nite dif-fer-ence',
    'finite element': 'fi-nite el-e-ment',
    'stochastic': 'sto-chas-tic',
    'deterministic': 'de-ter-min-is-tic',
    'regression': 're-gres-sion',
    'correlation': 'cor-re-la-tion',
    'covariance': 'co-var-i-ance',
    'autocorrelation': 'au-to-cor-re-la-tion',
    'heteroscedasticity': 'het-er-o-sce-das-tic-i-ty',
    'homoscedasticity': 'ho-mo-sce-das-tic-i-ty',
    'stationarity': 'sta-tion-ar-i-ty',
    'cointegration': 'co-in-te-gra-tion',
    'unit root': 'u-nit root',
    'Dickey-Fuller': 'Dick-ey-Ful-ler',
    'Augmented Dickey-Fuller': 'Au-gment-ed Dick-ey-Ful-ler',
    'Phillips-Perron': 'Phil-lips-Per-ron',
    'KPSS': 'K-P-S-S',
    'Johansen': 'Jo-han-sen',
    'Engle-Granger': 'En-gle-Gran-ger',
    'VAR': 'V-A-R',
    'VECM': 'V-E-C-M',
    'GARCH': 'G-A-R-C-H',
    'EGARCH': 'E-G-A-R-C-H',
    'GJR-GARCH': 'G-J-R-G-A-R-C-H',
    'APARCH': 'A-P-A-R-C-H',
    'FIGARCH': 'F-I-G-A-R-C-H',
    'FIEGARCH': 'F-I-E-G-A-R-C-H',
    'HYGARCH': 'H-Y-G-A-R-C-H',
    'CGARCH': 'C-G-A-R-C-H',
    'TGARCH': 'T-G-A-R-C-H',
    'NGARCH': 'N-G-A-R-C-H',
    'AVGARCH': 'A-V-G-A-R-C-H',
    'NAGARCH': 'N-A-G-A-R-C-H',
    'APGARCH': 'A-P-G-A-R-C-H',
    'GQARCH': 'G-Q-A-R-C-H',
    'GOGARCH': 'G-O-G-A-R-C-H',
    'GO-GARCH': 'G-O-G-A-R-C-H',
    'DCC-GARCH': 'D-C-C-G-A-R-C-H',
    'BEKK': 'B-E-K-K',
    'CCC': 'C-C-C',
    'DCC': 'D-C-C',
    'ADCC': 'A-D-C-C',
    'FDCC': 'F-D-C-C',
    'RCC': 'R-C-C',
    'GOF': 'G-O-F',
    'ICA': 'I-C-A',
    'PCA': 'P-C-A',
    'FA': 'F-A',
    'CCA': 'C-C-A',
    'PLS': 'P-L-S',
    'PCR': 'P-C-R',
    'Ridge': 'Ridge',
    'Lasso': 'Las-so',
    'Elastic Net': 'E-las-tic Net',
    'Random Forest': 'Ran-dom For-est',
    'Gradient Boosting': 'Gra-di-ent Boost-ing',
    'XGBoost': 'X-G-Boost',
    'LightGBM': 'Light-G-B-M',
    'CatBoost': 'Cat-Boost',
    'AdaBoost': 'A-da-Boost',
    'SVM': 'S-V-M',
    'Support Vector Machine': 'Sup-port Vec-tor Ma-chine',
    'KNN': 'K-N-N',
    'k-Nearest Neighbors': 'k-Near-est Neigh-bors',
    'Naive Bayes': 'Na-ive Bayes',
    'Logistic Regression': 'Lo-gis-tic Re-gres-sion',
    'Linear Regression': 'Lin-ear Re-gres-sion',
    'Polynomial Regression': 'Pol-y-no-mi-al Re-gres-sion',
    'Ridge Regression': 'Ridge Re-gres-sion',
    'Lasso Regression': 'Las-so Re-gres-sion',
    'Elastic Net Regression': 'E-las-tic Net Re-gres-sion',
    'Decision Tree': 'De-ci-sion Tree',
    'Extra Trees': 'Ex-tra Trees',
    'Neural Network': 'Neu-ral Net-work',
    'Deep Learning': 'Deep Learn-ing',
    'CNN': 'C-N-N',
    'Convolutional Neural Network': 'Con-vo-lu-tion-al Neu-ral Net-work',
    'RNN': 'R-N-N',
    'Recurrent Neural Network': 'Re-cur-rent Neu-ral Net-work',
    'LSTM': 'L-S-T-M',
    'Long Short-Term Memory': 'Long Short-Term Mem-o-ry',
    'GRU': 'G-R-U',
    'Gated Recurrent Unit': 'Gat-ed Re-cur-rent Unit',
    'Transformer': 'Trans-form-er',
    'BERT': 'B-E-R-T',
    'GPT': 'G-P-T',
    'GPT-2': 'G-P-T-two',
    'GPT-3': 'G-P-T-three',
    'GPT-4': 'G-P-T-four',
    'T5': 'T-five',
    'RoBERTa': 'Ro-B-E-R-T-a',
    'ALBERT': 'A-L-B-E-R-T',
    'ELECTRA': 'E-L-E-C-T-R-A',
    'DeBERTa': 'De-B-E-R-T-a',
    'XLNet': 'X-L-Net',
    'BART': 'B-A-R-T',
    'UL2': 'U-L-two',
    'PaLM': 'P-a-L-M',
    'LaMDA': 'La-M-D-A',
    'Chinchilla': 'Chin-chil-la',
    'Gopher': 'Go-pher',
    'Megatron': 'Meg-a-tron',
    'Switch Transformer': 'Switch Trans-form-er',
    'Mixture of Experts': 'Mix-ture of Ex-perts',
    'MoE': 'M-o-E',
    'Sparse MoE': 'Sparse M-o-E',
    'Dense MoE': 'Dense M-o-E',
    'Switch MoE': 'Switch M-o-E',
    'GLaM': 'G-La-M',
}

# Natural speech enhancement settings
NATURAL_SPEECH_ENHANCEMENTS = {
    'PAUSE_AFTER_SENTENCES': True,
    'PAUSE_AFTER_COMMAS': True,
    'EMPHASIS_ON_NUMBERS': True,
    'EMPHASIS_ON_PERCENTAGES': True,
    'EMPHASIS_ON_CURRENCY': True,
    'EMPHASIS_ON_ACRONYMS': True,
    'NATURAL_RHYTHM': True,
    'PROSODY_CONTROL': True,
    'EMOTION_MODULATION': True,
    'SPEAKER_CONSISTENCY': True,
}

# Performance optimization settings
PERFORMANCE_SETTINGS = {
    'ENABLE_CACHING': True,
    'CACHE_DURATION_HOURS': 24,
    'MAX_CONCURRENT_SYNTHESIS': 5,
    'BATCH_PROCESSING': True,
    'AUDIO_COMPRESSION': True,
    'LAZY_LOADING': True,
    'PRELOAD_COMMON_TERMS': True,
    'OPTIMIZE_FOR_MOBILE': True,
}

# Quality assurance settings
QUALITY_SETTINGS = {
    'AUDIO_QUALITY_CHECK': True,
    'PRONUNCIATION_VALIDATION': True,
    'EMOTION_CONSISTENCY_CHECK': True,
    'SPEED_OPTIMIZATION': True,
    'NOISE_REDUCTION': True,
    'NORMALIZE_VOLUME': True,
    'ENHANCE_CLARITY': True,
    'MAINTAIN_NATURALNESS': True,
}
