# Generated by Django 5.2.5 on 2025-08-31 00:15
from django.db import migrations, models
class Migration(migrations.Migration):
dependencies = [
('core', '0007_user_profile_pic'),
]
operations = [
migrations.AddField(
model_name='post',
name='image',
field=models.URLField(blank=True, max_length=500, null=True),
),
]
