[server]
host = "127.0.0.1"
port = 3001
log_level = "info"

[alpha_vantage]
api_key = "K0A7XYLDNXHNQ1WI"
base_url = "https://www.alphavantage.co/query"
# Alpha Vantage free tier: 5 API calls per minute, 500 per day
rate_limit_per_minute = 5
rate_limit_per_day = 500

[analysis]
# Minimum data points needed for technical analysis
min_historical_data_points = 50
# Beginner-friendly thresholds
min_market_cap = 1_000_000_000  # $1B
max_pe_ratio = 35.0
min_dividend_yield = 1.0
max_debt_ratio = 50.0
min_volume = 500_000
