#!/bin/bash

# RichesReach AI - Manual Demo Recording Helper
# Since automated recording didn't save, let's do it manually with better control

echo "🎬 Setting up Manual Demo Recording..."

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📱 Your iPhone 16 Pro Simulator is ready!${NC}"
echo -e "${BLUE}📱 Your RichesReach app is loaded and running!${NC}"

echo ""
echo -e "${YELLOW}🎬 Let's record your demo manually with better control:${NC}"
echo ""
echo "1. **Start Screen Recording**:"
echo "   - Press Cmd+Shift+5 (or Control Center > Screen Recording)"
echo "   - Select 'iPhone 16 Pro' simulator"
echo "   - Click 'Record'"
echo ""
echo "2. **Follow the Demo Sequence** (Total: ~60 seconds):"
echo ""
echo -e "${GREEN}🎤 Voice AI Trading Demo (15s):${NC}"
echo "   - Tap Voice AI tab (bottom)"
echo "   - Select Nova voice"
echo "   - Tap voice orb"
echo "   - Say: 'Buy 100 AAPL at limit 150'"
echo "   - Tap Execute Trade"
echo "   - View Portfolio"
echo ""
echo -e "${GREEN}🎭 MemeQuest Social Demo (17s):${NC}"
echo "   - Tap MemeQuest tab"
echo "   - Pick Frog template"
echo "   - Tap voice orb"
echo "   - Say: 'Launch Meme!'"
echo "   - Tap Animate button"
echo "   - Tap Send Tip button"
echo "   - Show confetti burst"
echo ""
echo -e "${GREEN}🤖 AI Trading Coach Demo (10s):${NC}"
echo "   - Tap Coach tab"
echo "   - Drag risk slider right"
echo "   - Select Bullish Spread strategy"
echo "   - Tap Execute Trade"
echo ""
echo -e "${GREEN}📚 Learning System Demo (17s):${NC}"
echo "   - Tap Learning tab"
echo "   - Start Options Quiz"
echo "   - Answer: Call Option"
echo "   - Tap Next"
echo "   - Answer: Put Option"
echo "   - Show Results & XP gain"
echo ""
echo -e "${GREEN}👥 Social Features Demo (12s):${NC}"
echo "   - Tap Community tab"
echo "   - Join BIPOC Wealth Builders league"
echo "   - Join discussion"
echo "   - Type: 'Great insights!'"
echo "   - Send message"
echo ""
echo "3. **Stop Recording**:"
echo "   - Press Cmd+Shift+5 again or click stop in Control Center"
echo "   - Save to Desktop as 'RichesReach_Demo_$(date +%Y%m%d).mov'"
echo ""
echo -e "${BLUE}🎯 Key Features to Highlight:${NC}"
echo "   ✅ Voice AI Trading (6 voices)"
echo "   ✅ Real-time market data (<50ms)"
echo "   ✅ AI-powered analysis"
echo "   ✅ Social trading community"
echo "   ✅ Gamified learning system"
echo "   ✅ BIPOC-focused content"
echo ""
echo -e "${YELLOW}📊 Key Metrics to Include:${NC}"
echo "   • 68% Retention Rate"
echo "   • 25-40% DAU Increase"
echo "   • 50% Faster Execution"
echo "   • 15% Better Performance"
echo "   • \$1.2T Market Opportunity"
echo ""
echo -e "${GREEN}🚀 Ready to record your professional demo!${NC}"
echo -e "${BLUE}💡 This will be perfect for YC/Techstars submission!${NC}"
