import React from 'react';
import { Image, Text, View, StyleSheet, ImageStyle, TextStyle } from 'react-native';

interface CryptoIconProps {
  symbol: string;
  size?: number;
  style?: ImageStyle;
  fallbackStyle?: TextStyle;
  showFallback?: boolean;
}

const CryptoIcon: React.FC<CryptoIconProps> = ({
  symbol,
  size = 24,
  style,
  fallbackStyle,
  showFallback = true,
}) => {
  const upperSymbol = symbol.toUpperCase();
  
  // CoinGecko API for crypto icons (free, no API key required)
  const iconUrl = `https://assets.coingecko.com/coins/images/1/large/bitcoin.png`;
  
  // Map of common crypto symbols to their CoinGecko coin IDs
  const symbolToCoinId: Record<string, string> = {
    'BTC': 'bitcoin',
    'ETH': 'ethereum',
    'USDT': 'tether',
    'USDC': 'usd-coin',
    'BNB': 'binancecoin',
    'XRP': 'ripple',
    'ADA': 'cardano',
    'SOL': 'solana',
    'DOGE': 'dogecoin',
    'DOT': 'polkadot',
    'AVAX': 'avalanche-2',
    'MATIC': 'matic-network',
    'LINK': 'chainlink',
    'UNI': 'uniswap',
    'LTC': 'litecoin',
    'BCH': 'bitcoin-cash',
    'ATOM': 'cosmos',
    'XLM': 'stellar',
    'ALGO': 'algorand',
    'VET': 'vechain',
    'ICP': 'internet-computer',
    'FIL': 'filecoin',
    'TRX': 'tron',
    'ETC': 'ethereum-classic',
    'XMR': 'monero',
    'EOS': 'eos',
    'AAVE': 'aave',
    'SUSHI': 'sushi',
    'COMP': 'compound-governance-token',
    'MKR': 'maker',
    'YFI': 'yearn-finance',
    'SNX': 'havven',
    'UMA': 'uma',
    'BAL': 'balancer',
    'CRV': 'curve-dao-token',
    '1INCH': '1inch',
    'SAND': 'the-sandbox',
    'MANA': 'decentraland',
    'ENJ': 'enjincoin',
    'CHZ': 'chiliz',
    'BAT': 'basic-attention-token',
    'ZRX': '0x',
    'REP': 'augur',
    'KNC': 'kyber-network-crystal',
    'LRC': 'loopring',
    'OMG': 'omg',
    'ZIL': 'zilliqa',
    'ONT': 'ontology',
    'QTUM': 'qtum',
    'ICX': 'icon',
    'WAVES': 'waves',
    'NEO': 'neo',
    'DASH': 'dash',
    'ZEC': 'zcash',
    'DCR': 'decred',
    'NANO': 'nano',
    'IOTA': 'iota',
    'XTZ': 'tezos',
    'EGLD': 'elrond-erd-2',
    'HBAR': 'hedera-hashgraph',
    'THETA': 'theta-token',
    'FTM': 'fantom',
    'NEAR': 'near',
    'FLOW': 'flow',
    'KSM': 'kusama',
    'AR': 'arweave',
    'RUNE': 'thorchain',
    'CAKE': 'pancakeswap-token',
    'BAKE': 'bakerytoken',
    'AUTO': 'auto',
    'ALPHA': 'alpha-finance',
    'BAND': 'band-protocol',
    'REN': 'republic-protocol',
    'KAVA': 'kava',
    'ROSE': 'oasis-network',
    'CELO': 'celo',
    'ONE': 'harmony',
    'IOTX': 'iotex',
    'SKL': 'skale',
    'OCEAN': 'ocean-protocol',
    'GRT': 'the-graph',
    'LPT': 'livepeer',
    'STORJ': 'storj',
    'ANKR': 'ankr',
    'RLC': 'iexec-rlc',
    'GNO': 'gnosis',
    'KEEP': 'keep-network',
    'NU': 'nucypher',
    'BADGER': 'badger-dao',
    'FARM': 'harvest-finance',
    'PICKLE': 'pickle-finance',
    'CREAM': 'cream-2',
    'ALPHA': 'alpha-finance',
    'COVER': 'cover-protocol',
    'BOND': 'barnbridge',
    'KP3R': 'keep3rv1',
    'HEGIC': 'hegic',
    'YAM': 'yam-2',
    'SUSHI': 'sushi',
    'SASHIMI': 'sashimi',
    'AKRO': 'akropolis',
    'ADX': 'adex',
    'LINA': 'linear',
    'PERP': 'perpetual-protocol',
    'RGT': 'rari-governance-token',
    'FRAX': 'frax',
    'FXS': 'frax-share',
    'ALCX': 'alchemix',
    'SPELL': 'spell-token',
    'MIM': 'magic-internet-money',
    'TOKE': 'tokemak',
    'OHM': 'olympus',
    'TIME': 'wonderland',
    'KLIMA': 'klima-dao',
    'BTRFLY': 'redacted-cartel',
    'INV': 'inverse-finance',
    'FEI': 'fei-usd',
    'TRIBE': 'tribe-2',
    'LQTY': 'liquity',
    'LUSD': 'liquity-usd',
    'CVX': 'convex-finance',
    'CRV': 'curve-dao-token',
    '3CRV': 'lp-3pool-curve',
    'FRAX3CRV': 'frax-3crv-f',
    'LUSD3CRV': 'lusd3crv-f',
    'GUSD': 'gemini-dollar',
    'BUSD': 'binance-usd',
    'DAI': 'dai',
    'TUSD': 'true-usd',
    'PAX': 'paxos-standard',
    'HUSD': 'husd',
    'USDK': 'usdk',
    'USDN': 'neutrino-usd',
    'RSV': 'reserve',
    'SUSD': 'nusd',
    'CUSD': 'celo-dollar',
    'CEUR': 'celo-euro',
    'MUSD': 'musd',
    'DUSD': 'defidollar',
    'FRAX': 'frax',
    'LQTY': 'liquity',
    'LUSD': 'liquity-usd',
    'ALUSD': 'alchemix-usd',
    'DOLA': 'dola-usd',
    'FLOAT': 'float-protocol',
    'RAI': 'rai',
    'FEI': 'fei-usd',
    'TRIBE': 'tribe-2',
    'OHM': 'olympus',
    'TIME': 'wonderland',
    'KLIMA': 'klima-dao',
    'BTRFLY': 'redacted-cartel',
    'INV': 'inverse-finance',
    'CVX': 'convex-finance',
    'CRV': 'curve-dao-token',
    'FXS': 'frax-share',
    'ALCX': 'alchemix',
    'SPELL': 'spell-token',
    'MIM': 'magic-internet-money',
    'TOKE': 'tokemak',
    'BOND': 'barnbridge',
    'KP3R': 'keep3rv1',
    'HEGIC': 'hegic',
    'YAM': 'yam-2',
    'SUSHI': 'sushi',
    'SASHIMI': 'sashimi',
    'AKRO': 'akropolis',
    'ADX': 'adex',
    'LINA': 'linear',
    'PERP': 'perpetual-protocol',
    'RGT': 'rari-governance-token',
    'BADGER': 'badger-dao',
    'FARM': 'harvest-finance',
    'PICKLE': 'pickle-finance',
    'CREAM': 'cream-2',
    'COVER': 'cover-protocol',
    'YFI': 'yearn-finance',
    'COMP': 'compound-governance-token',
    'MKR': 'maker',
    'SNX': 'havven',
    'UMA': 'uma',
    'BAL': 'balancer',
    '1INCH': '1inch',
    'AAVE': 'aave',
    'UNI': 'uniswap',
    'LINK': 'chainlink',
    'SAND': 'the-sandbox',
    'MANA': 'decentraland',
    'ENJ': 'enjincoin',
    'CHZ': 'chiliz',
    'BAT': 'basic-attention-token',
    'ZRX': '0x',
    'REP': 'augur',
    'KNC': 'kyber-network-crystal',
    'LRC': 'loopring',
    'OMG': 'omg',
    'ZIL': 'zilliqa',
    'ONT': 'ontology',
    'QTUM': 'qtum',
    'ICX': 'icon',
    'WAVES': 'waves',
    'NEO': 'neo',
    'DASH': 'dash',
    'ZEC': 'zcash',
    'DCR': 'decred',
    'NANO': 'nano',
    'IOTA': 'iota',
    'XTZ': 'tezos',
    'EGLD': 'elrond-erd-2',
    'HBAR': 'hedera-hashgraph',
    'THETA': 'theta-token',
    'FTM': 'fantom',
    'NEAR': 'near',
    'FLOW': 'flow',
    'KSM': 'kusama',
    'AR': 'arweave',
    'RUNE': 'thorchain',
    'CAKE': 'pancakeswap-token',
    'BAKE': 'bakerytoken',
    'AUTO': 'auto',
    'BAND': 'band-protocol',
    'REN': 'republic-protocol',
    'KAVA': 'kava',
    'ROSE': 'oasis-network',
    'CELO': 'celo',
    'ONE': 'harmony',
    'IOTX': 'iotex',
    'SKL': 'skale',
    'OCEAN': 'ocean-protocol',
    'GRT': 'the-graph',
    'LPT': 'livepeer',
    'STORJ': 'storj',
    'ANKR': 'ankr',
    'RLC': 'iexec-rlc',
    'GNO': 'gnosis',
    'KEEP': 'keep-network',
    'NU': 'nucypher',
  };

  const coinId = symbolToCoinId[upperSymbol];
  
  if (!coinId) {
    if (showFallback) {
      return (
        <View style={[styles.fallbackContainer, { width: size, height: size }, style]}>
          <Text style={[styles.fallbackText, { fontSize: size * 0.4 }, fallbackStyle]}>
            {upperSymbol.substring(0, 2)}
          </Text>
        </View>
      );
    }
    return null;
  }

  const finalIconUrl = `https://assets.coingecko.com/coins/images/1/large/${coinId}.png`;

  return (
    <Image
      source={{ uri: finalIconUrl }}
      style={[
        styles.icon,
        {
          width: size,
          height: size,
        },
        style,
      ]}
      resizeMode="contain"
      onError={() => {
        // If the image fails to load, we could implement a fallback here
        console.warn(`Failed to load icon for ${upperSymbol}`);
      }}
    />
  );
};

const styles = StyleSheet.create({
  icon: {
    borderRadius: 12,
  },
  fallbackContainer: {
    backgroundColor: '#E5E7EB',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fallbackText: {
    fontWeight: '600',
    color: '#6B7280',
  },
});

export default CryptoIcon;
