version: '3.8'
services:
richesreach-ai:
build: .
ports:
- "8000:8000"
environment:
- ENVIRONMENT=production
- PORT=8000
- HOST=0.0.0.0
restart: unless-stopped
healthcheck:
test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
interval: 30s
timeout: 10s
retries: 3
start_period: 40s
labels:
- "traefik.enable=true"
- "traefik.http.routers.richesreach.rule=Host(`richesreach.ai`)"
- "traefik.http.services.richesreach.loadbalancer.server.port=8000"
