# Generated by Django 5.2.3 on 2025-08-30 16:43
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
class Migration(migrations.Migration):
dependencies = [
('core', '0002_post'),
]
operations = [
migrations.CreateModel(
name='ChatSession',
fields=[
('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
('title', models.CharField(blank=True, max_length=255)),
('created_at', models.DateTimeField(auto_now_add=True)),
('updated_at', models.DateTimeField(auto_now=True)),
('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
],
),
migrations.CreateModel(
name='ChatMessage',
fields=[
('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
('content', models.TextField()),
('created_at', models.DateTimeField(auto_now_add=True)),
('confidence', models.FloatField(blank=True, null=True)),
('tokens_used', models.IntegerField(blank=True, null=True)),
('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
],
options={
'ordering': ['created_at'],
},
),
migrations.CreateModel(
name='Source',
fields=[
('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
('title', models.CharField(max_length=255)),
('url', models.URLField()),
('snippet', models.TextField()),
('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.chatmessage')),
],
),
]
