# Generated by Django 4.2.1 on 2025-08-30 18:54
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    dependencies = [
    ('core', '0004_like'),
    ]
    operations = [
    migrations.CreateModel(
    name='Comment',
    fields=[
    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    ('content', models.TextField()),
    ('created_at', models.DateTimeField(auto_now_add=True)),
    ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.post')),
    ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
    ],
    options={
    'verbose_name': 'Comment',
    'verbose_name_plural': 'Comments',
    'db_table': 'core_comment',
    'ordering': ['created_at'],
    },
    ),
    ]
