# Generated by Django 5.2.5 on 2025-09-02 01:47
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
    ('core', '0012_alter_portfolio_options_and_more'),
    ]
    operations = [
    migrations.AddField(
    model_name='stock',
    name='current_price',
    field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
    ),
    ]
