# Generated by Django 5.2.6 on 2025-09-07 14:21
from django.db import migrations
class Migration(migrations.Migration):
    dependencies = [
    ('core', '0015_add_income_profile'),
    ]
    operations = [
    ]
