# Generated by Django 5.2.6 on 2025-09-08 01:25
from django.db import migrations
class Migration(migrations.Migration):
    dependencies = [
    ('core', '0016_auto_20250907_1421'),
    ]
    operations = [
    ]
