# Generated by Django 4.2.1 on 2025-09-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20250908_0125'),
    ]

    operations = [
    ]
