# Generated by Django 4.2.1 on 2025-09-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_aiportfoliorecommendation_discussioncomment_and_more'),
    ]

    operations = [
    ]
