name: Build & Push Docker to ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for clean diffs

    - name: Compute celery.py SHA
      id: shas
      run: |
        echo "celery_sha=$(sha256sum backend/backend/richesreach/celery.py | awk '{print $1}')" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_GH_ACTIONS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: riches-reach-streaming
        IMAGE_TAG: ${{ github.sha }}
        CELERY_SHA: ${{ steps.shas.outputs.celery_sha }}
      run: |
        docker buildx create --use
        docker buildx build \
          --platform linux/amd64 \
          --no-cache \  # Bust all layers for fresh code
          --build-arg CELERY_SHA=$CELERY_SHA \
          -f backend/backend/Dockerfile.production \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
          --push backend/backend
