name: Test Build Only

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 498606688292
  ECR_REPO: riches-reach-ai

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify build context
        run: |
          echo "🔍 Checking build context size..."
          du -sh .
          echo "📁 Backend directory size:"
          du -sh backend/backend/
          echo "📋 Key files:"
          ls -la backend/backend/richesreach/__init__.py
          ls -la backend/backend/richesreach/celery.py
          echo "📄 __init__.py content (first 10 lines):"
          head -10 backend/backend/richesreach/__init__.py

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/backend/Dockerfile.production
          build-args: |
            GIT_SHA=${{ github.sha }}
          push: false
          tags: test-build:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify image contents
        run: |
          echo "🔍 Testing image contents..."
          docker run --rm test-build:${{ github.sha }} python -c "
          import os
          print('DJANGO_SETTINGS_MODULE:', os.environ.get('DJANGO_SETTINGS_MODULE'))
          print('Testing lazy import...')
          import richesreach
          print('richesreach module loaded successfully')
          print('Testing celery import...')
          from richesreach import get_celery_app
          print('Lazy celery import works!')
          "